### ISSUE TITLE
Time to live for jobs

### ISSUE THREAD

**Issue by weeco** [OptimalBits/bull#726] opened 2017-10-12 15:06 UTC
As far as I understand the below Job option it is supposed to timeout a running job if it takes too long to process. So it wouldn't matter how long it takes until the queue actually begins processing the job, it just matters how long it takes to finish this job.

`timeout: number; // The number of milliseconds after which the job should be fail with a timeout error [optional]`

**The feature I am looking for:**

What I am looking for is some kind of time to live, which should also be easy to implement as redis already offers a TTL. So let's say I add 100,000 jobs and I want them to be processed within the next 3 hours. All jobs which couldn't be processed within these 3 hours shall be deleted from the Queue.

**Comment by manast** [comment] 2017-10-13 07:37
I will close this one as a duplicate of https://github.com/OptimalBits/bull/issues/684

**Closed by manast** 2017-10-13 07:37 UTC
