### ISSUE TITLE
Promise was created in a handler but was not returned

### ISSUE THREAD

**Issue by Sicria** [OptimalBits/bull#618] opened 2017-07-14 05:03 UTC
Sometimes I get this warning popup, not sure if it's something I'm doing that's possibly causing it.

``(node:25) Warning: a promise was created in a handler at node_modules/bull/lib/queue.js:279:17 but was not returned from it, see http://goo.gl/rRqMUw``

https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L279

**Comment by zidsi** [comment] 2017-08-30 10:09
Possible duplicate of #518

**Comment by manast** [comment] 2017-11-05 21:14
should be fixed already.

**Closed by manast** 2017-11-05 21:14 UTC
