### ISSUE TITLE
The job is going in a waiting state after new container instance comes up

### ISSUE THREAD

**Issue by akashwmp** [OptimalBits/bull#1823] opened 2020-08-16 12:42 UTC
When a single container instance is running, all the processors registered themselves to the desired channel. But if a new container instance comes up, the queue starts going into a waiting state. To resolve this issue, either we need to delete the whole queue or channel or restart the container. The issue is also the same in the scenario where we have multiple running containers and if one container goes down, then a new container not able to register it's the processor to the existing channel. I'm not sure if this is the limitation of BULL QUEUE in a distributed microservices environment?

**Comment by manast** [comment] 2020-08-16 18:37
It would be great if you can try to explain your problem with an example because I am not really following the problem you have... Basically if you have an online redis instance your workers will just connect to it and process jobs. If the redis instance is down when you start your workers they will fail and you will have to handle this failure in your code.

**Comment by akashwmp** [comment] 2020-08-16 20:42
@manast Thank you for the quick response. Here is a code snippet of our current implementation. This is the same as I used in problem #1824. Whenever new docker instances come up, the bull queue processor is not able to register to the existing queue or channel and unfortunately, queues start going into a waiting state but if I restart the container, things will start working fine.
Producer level or pushing a job into the queue

const publishToQueue = (queueName, queueMsg, opt = { attempts: 4, backoff: { type: 'fixed', delay: 100 },removeOnComplete: true,removeOnFail:true }) => {
let opts = {
createClient: function () {
return ioRedisClient;
}
};
let queue = new Queue(queueName, opts);
queue.add(queueMsg, opt);
};

Here we have written a common wrapper function for pushing the job in the queue and we are using this particular functionality across different modules with the same Redis instance

Consumer-level or Subscriber

class worker {
createQueue(name) {
var opts = {
createClient: function (type) {
switch (type) {
case 'client':
return client;
case 'subscriber':
return subscriber;
default:
return new Redis(REDIS_URL);
}
}
};
return new Queue(name, opts);
}
subscribe() {
let ConsumerQueue = this.createQueue('xyz-queue');//the common channel or queue
ConsumerQueue.process(QueueProcessor); // path to queue processor written in other file
}
}
The subscribe method has been triggered once a server instance starts

QueueProcessor.js

module.exports = async (job) => {
let queueData = job.data;
// Check if processor queue contains job data
if(Object.keys(queueData).length) {
let state = await job.getState();
if (state === 'completed') {
return Promise.resolve();
}
processData(queueData); // function to process queue data
return Promise.resolve();
} else {
console.error(queue received bad or empty job data' + job.id);
}
};

Here the job is published into the queue for once but getting processed multiple times by the attached processor. We are using the AWS Redis elastic cache. This behavior is persistent if we run one docker instance or multiple docker instances of the worker module. The consumer or subscriber module is independent of the producer and both are connected to the same Redis instance.

Current library version ( using the latest ones )
"bull": "^3.10.0",
"ioredis": "^4.10.0",
"redis": "^2.8.0"

**Comment by manast** [comment] 2020-08-16 21:32
duplicate of #1824

**Closed by manast** 2020-08-16 21:32 UTC
