### ISSUE TITLE
Jobs get stuck after Redis reconnect

### ISSUE THREAD

**Issue by Yuliang-Lee** [OptimalBits/bull#2417] opened 2022-08-23 10:12 UTC
## Description

The problem similar to https://github.com/OptimalBits/bull/issues/1873

## Steps to reproduce.

- Run the above script
- Bull JS start accepting and processing Jobs
- Stop Redis
- Bull JS will keep retrying
- Start Redis
- Bull JS will connect in a few milliseconds
- At this stage, the queue can push the jobs and but it won't process any jobs. :-(

## Bull version

Bull 4.8.5
Node 16
Redis 7
ioredis 4.x / 5.x

## Additional information

When initial `Queue` I tried `redis`-option or `createRedis`-option but neither works.

blow are my console log.

queue options
```
{
        port: 6379, // Redis port
        host: 'ip', // Redis host
        password: 'password',
        db: 0,
        enableReadyCheck: false,
        maxRetriesPerRequest: null,
        reconnectOnError() {
          return true
        }
      }
```

[ioredis.log](https://github.com/OptimalBits/bull/files/9401598/ioredis.log)

[ioredis-createClient.log](https://github.com/OptimalBits/bull/files/9401600/ioredis-createClient.log)

**Comment by manast** [comment] 2022-08-23 10:20
I am going to close this since no new information is provided. From my end I cannot reproduce any issue of stuck jobs when reconnecting, so please if you want me to spend time investigating this, provide a full complete and easy to reproduce code snippet and instructions.

**Closed by manast** 2022-08-23 10:20 UTC

**Comment by Yuliang-Lee** [comment] 2022-08-24 04:12
The `isredis.log` content could find out when redis reconnect subscriber  not work

**Comment by Yuliang-Lee** [comment] 2022-08-24 15:33
memo: https://github.com/OptimalBits/bull/issues/1873#issuecomment-1225886844
