### ISSUE TITLE
Methods of Mongoose models not defined inside job.process

### ISSUE THREAD

**Issue by miladr0** [OptimalBits/bull#1356] opened 2019-06-20 19:02 UTC
## Description
i want to update my user login datetime using background job, i'm using mongodb/mongoose as primary database but when i call methods of my model inside of process body it said  for example : `TypeError: User.findOneAndUpdate is not a function`

## Minimal, Working Test code to reproduce the issue.
```javascript
const { opts } = require('./redisConnection');
const Queue = require('bull');
 const User = require('../../models/user.model');

const lastLoginQueue = new Queue('last-login', opts);

lastLoginQueue.process(async (job) => {
  console.log('Received ', job.data.userId);
  const { userId } = job.data;

  const user = await User.findOneAndUpdate(
        { _id: userId },
        {
          $currentDate: {
            lastLogin: true,
          },
        },
      );
  return Promise.resolve();
});
```
#### (An easy to reproduce test case will dramatically decrease the resolution time.)
when run above code it said:
`[ 'TypeError: User.findOneAndUpdate is not a function\n`
## Additional information
maybe because methods of mongoose models is virtual or something else happend.

**Comment by manast** [comment] 2019-06-20 20:59
I am going to close this issue since it is unrelated to bull.

**Closed by manast** 2019-06-20 20:59 UTC

**Comment by miladr0** [comment] 2019-06-20 21:04
it's related to bull, anyway i found the solution. somehow methods of mongoose models not working inside job.process i used mongodb native driver and it's worked.

**Comment by ronaldho** [comment] 2019-09-10 19:58
Thank you for this issue!! I also ran into this trouble and was debugging forever trying to use async/await and also trying callback and nothing worked!

once i switched to the native drivers, it worked

**Comment by rd67** [comment] 2020-06-02 15:51
Same Case Here. My mongoose model imported is set as undefined. Any other method than using mongodb native package?

**Comment by rd67** [comment] 2020-06-02 16:42
Got it, it was because of circular dependency somewhere in my code. If someone else faces the same situation.

**Comment by kasvith** [comment] 2020-09-15 21:08
thanks, just happened to me

**Comment by MarioFronza** [comment] 2020-09-21 13:19
There's no way to use mongoose? only the native driver?

**Comment by RizaHKhan** [comment] 2020-09-25 13:18
> Same Case Here. My mongoose model imported is set as undefined. Any other method than using mongodb native package?

So you are saying you were able to use Mongoose to query the database?

**Comment by manast** [comment] 2020-09-25 13:48
@RizaHKhan As far as I know this only happens using external sandboxed processors. And the cause must be due to some exotic thing in mongoose, bull is not doing anything special just spawning a process and running the processor inside it.

**Comment by miladr0** [comment] 2020-09-25 14:03
@manast maybe mongoose need some time to initialize the connection and models, I'm not using Bull right now but if had time will checking some ways like passing mongoose as a parameter to the `process` method

**Comment by kasvith** [comment] 2020-09-30 09:13
@manast I found that my socket-io instance is not also shared to the spawned process. This might be the same problem with mongoose.

Globals, Variables defined in the main process does not pass to the child

**Comment by manast** [comment] 2020-09-30 09:46
@kasvith yes, thats kind of the point of running a separate process so that you get complete isolation. But I am not sure that is the problem with mongoose though since as reported here the poster is not using a external process, just a callback, which is nothing special so I don't understand why it does not work, however I have seen very strange behaviours with mongoose in the past.

**Comment by RizaHKhan** [comment] 2020-09-30 12:45
My issue was resolved simply by reinitializing Mongoose under the worker process. Hope that helps anyone else that might have this issue.

PS: I found the solution based on a response by @manast on a similar post.

**Comment by hardnold** [comment] 2020-10-20 21:54
> My issue was resolved simply by reinitializing Mongoose under the worker process. Hope that helps anyone else that might have this issue.
> 
> PS: I found the solution based on a response by @manast on a similar issue.

Could you please be more specific on what you did exactly and maybe link to the similar issue you're referring to?

**Comment by miladr0** [comment] 2020-10-20 23:11
@hardnold 
I'm writing an article about using bull with mongodb, tomorrow in my timezone I can publish it. But until then you can take look the repo for that article and how I used mongoos with bull.
Cheers 🍻 
https://github.com/miladr0/bull-mongo

**Comment by ada-mr0r** [comment] 2020-10-21 15:13
link to the tutorial: https://medium.com/better-programming/message-queue-using-bull-redis-and-mongodb-in-node-js-d7dedaa426ea

once again tnx for ur awesome library @manast

**Comment by miladr0** [comment] 2020-10-21 15:15
link to the tutorial: https://medium.com/better-programming/message-queue-using-bull-redis-and-mongodb-in-node-js-d7dedaa426ea

once again tnx for your awesome library @manast

**Comment by hardnold** [comment] 2020-10-21 16:38
> link to the tutorial: https://medium.com/better-programming/message-queue-using-bull-redis-and-mongodb-in-node-js-d7dedaa426ea
> 
> once again tnx for your awesome library @manast

Thanks. Nice Article. Didn't help to fix my problem though 😉  (I didn't get the OP's described Type Error, instead just nothing happened). 
What actually solved my Problem was to open a new DB-Connection for the processor (which is in a separate File).
