### ISSUE TITLE
Too many ZREMs since upgrading to 2.2.2

### ISSUE THREAD

**Issue by mdemri** [OptimalBits/bull#463] opened 2017-03-09 15:03 UTC
We've got hundreds of ZREM commands in bull objects..
Since we've upgraded to 2.2.2 (from 2.1.2)

9074997.036956 [0 52.19.113.23:49904] "zrem" "bull:stlr:s:campaigns:inbox:priority" "249"
9074997.036956 [0 52.19.113.23:49904] "zrem" "bull:stlr:s:campaigns:inbox:priority" "249"
9074997.036956 [0 52.19.113.23:49904] "zrem" "bull:stlr:s:campaigns:inbox:priority" "250"
9074997.036956 [0 52.19.113.23:49904] "zrem" "bull:stlr:s:campaigns:inbox:priority" "250"

**Comment by sloops77** [comment] 2017-03-09 15:12
HI - i work with mdemri. 
More info: 
* We dont use priority queues at all
* Looks related to the code in queue.js:804

**Comment by manast** [comment] 2017-03-09 15:15
It is correct that we issue an extra zrem, since it is currently impossible to know if jobs have priorities or not we just remove them, this should not affect performance in any way since the zset is empty.

**Comment by sloops77** [comment] 2017-03-09 15:21
it seems to have made our redis instance perform poorly

<img width="1123" alt="screen shot 2017-03-09 at 17 19 14" src="https://cloud.githubusercontent.com/assets/4784403/23756564/c470f83e-04ec-11e7-8735-d32c4d6aa682.png">
<img width="1162" alt="screen shot 2017-03-09 at 17 19 06" src="https://cloud.githubusercontent.com/assets/4784403/23756565/c475be8c-04ec-11e7-86e5-0fc777c19ffc.png">

**Comment by manast** [comment] 2017-03-09 16:21
hmm, in that case it cannot come from https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L804 since that is just issued as a command, not inside any script.

**Comment by mdemri** [comment] 2017-03-09 17:47
I've downgraded bull to 2.12 and this issue stopped happening

**Comment by ryanmills** [comment] 2017-03-09 22:29
Hey @sloops77 -- What are you using to generate those redis performance graphs?

**Comment by sloops77** [comment] 2017-03-10 08:41
http://www.redisgreen.net/

**Comment by manast** [comment] 2017-03-10 08:52
@mdemri I just wondering, are you getting more ZREM calls than jobs processed? because it should be 1 ZREM call per job that starts to be processed by the queue. That should be normal and not create any major performance impact.

**Comment by mdemri** [comment] 2017-03-12 14:05
@manast I'm pretty sure i have more ZREMs than jobs processed.

The ZREMs made the difference between working environment and non working environment (2.2.2 vs 2.1.2)

**Comment by manast** [comment] 2017-03-12 15:57
@mdemri can you get the full ZREM command including its parameters that is being issued so many times?

**Comment by manast** [comment] 2017-03-12 20:16
@mdemri ok I assume they are these ones:
```
9074997.036956 [0 52.19.113.23:49904] "zrem" "bull:stlr:s:campaigns:inbox:priority" "249"
```
These ZREMs can only be executed once per job, unless the job is failing and being retried. At least by examining the code and also I am not able to reproduce it myself. If you could write a simple test that reproduces it I can take a deeper look at it.

**Comment by manast** [comment] 2017-05-24 12:36
I do not think this is relevant for 3.0.0 so I will close it. Re-open if the issue still appears in the last version.

**Closed by manast** 2017-05-24 12:36 UTC
