### ISSUE TITLE
orders in reate limit

### ISSUE THREAD

**Issue by Bahramibh** [OptimalBits/bull#1799] opened 2020-07-13 13:24 UTC
when im using rate limit , the orders ignored , and for example if i have 1 to 100 (id of jobs) ,when rate limit is active, 
its process like this   (in the middle of process : ) = 44,46,89,1,56,57,58

**Comment by Bahramibh** [comment] 2020-07-14 06:40
i read all issueds about rate limit problem 
i think its bull bad pattern 
bull add random delay time , or a invalid delay time for jobs (get rate limit)
and some of them never process (never means they process after a time : delay time + process new jobs (grows) + ....)
why bull dont get jobs from redis by time they created ?

**Comment by Bahramibh** [comment] 2020-07-14 06:40
`const Bull = require("bull");
const express = require("express");
const { setQueues, UI, createQueues } = require("bull-board");
console.log(new Date());
const app = express();

let count = 1;
const myFirstQueue = new Bull("my-first-queue", {
	limiter: {
		max: 3,
		duration: 1000,
		bounceBack: false,
	},
	// settings: {
	// 	stalledInterval: 500,
	// },
});

// myFirstQueue.on("completed", () => console.log("completed"));
async function addjob() {
	await myFirstQueue.add(
		{
			foo: "bar",
			count: count++,
			d: new Date(),
		},
		{ removeOnComplete: true }
	);
}

setInterval(async () => {
	await addjob();
}, 100);

myFirstQueue.process(async (job) => {
	// console.log("process@", new Date());
	// job.retry();
	return console.log(job.data);
});

const redisConfig = {
	redis: {
		port: 6379,
		host: "127.0.0.1",
	},
};

setQueues(myFirstQueue);

app.use("/", UI);
const PORT = 1231;
app.listen(PORT, function () {
	console.log("running on port ", PORT);
});
`

**Comment by manast** [comment] 2020-07-15 17:28
I am closing this because there is not a clear reproducible bug.

**Closed by manast** 2020-07-15 17:28 UTC
