### ISSUE TITLE
Queue process concurrency

### ISSUE THREAD

**Issue by ritter** [OptimalBits/bull#760] opened 2017-10-26 16:10 UTC
```
const Queue = require('bull');
const test = new Queue('test');
test.process('job1', 1, () => { done(); });
test.process('job2', 10, () => { done(); });
```
Job concurrency of job1 will be 10 per worker, expected 1 per worker.

**Comment by manast** [comment] 2017-10-26 18:48
I think it is not 10 but 11 in this particular case

**Comment by ritter** [comment] 2017-10-26 18:50
Am I misunderstanding the process concurrency?  For the time being, I've separated the processes to unique queues.

**Comment by manast** [comment] 2017-10-26 18:53
yes, it is not trivial to have different concurrency levels for different named jobs, we may end changing the api so that this behaviour does not come as a surprise.

**Comment by ritter** [comment] 2017-10-26 19:01
Okay, thanks for the clarification.  I'm okay if this issue is closed.

**Comment by manast** [comment] 2017-10-26 19:07
I can leave it as an enhancement to avoid future duplicates.

**Comment by Asp3ctus** [comment] 2017-10-31 23:52
i would love to see this improved as well

**Comment by weeco** [comment] 2017-11-03 23:26
Also see https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueprocess , if you scroll down a bit it's explained there.

**Comment by Asp3ctus** [comment] 2017-11-13 11:23
@weeco yes - it's explained - but still it should not work like that. and that explanation was added after my issue #719

**Comment by weeco** [comment] 2017-11-13 14:05
It is working by design. I don't like this and a few other behaviours either, but since these would be breaking changes I don't see them changing anytime soon.

**Comment by Asp3ctus** [comment] 2017-12-01 19:56
well may be it could be a seperate feature or tunable behavior- i think some other people can find it usefull as well.
Let's vote :) +1

**Comment by swayam18** [comment] 2018-03-23 09:01
+1

**Comment by manast** [comment] 2018-03-23 17:59
If it was easy to implement, but the problem is that it requires several important changes in the core, so I do not think it is worth the effort, specially when you can just have 2 different queues to get the desired behaviour.

**Comment by chgcamp** [comment] 2018-04-25 19:00
Except, with multiple queues seems you lose the ability to prioritize and have max concurrency across named jobs.

**Comment by MicahMartin** [comment] 2019-09-16 19:40
bump...

**Comment by manast** [comment] 2019-09-16 20:45
I am going to close this, since the issue has become unclear, and there is no proposed solution for it.

**Closed by manast** 2019-09-16 20:45 UTC
Labels: enhancement

**Comment by tskweres** [comment] 2020-03-03 22:06
What is the maximum amount of concurrency for a process? Anyone know?

**Comment by ciarans** [comment] 2020-07-23 17:27
@tskweres did you ever find an answer for this?
