### ISSUE TITLE
Backoff strategy example

### ISSUE THREAD

**Issue by mirkods** [OptimalBits/bull#696] opened 2017-09-21 09:29 UTC
Hi there,
first of all congratulation for this awesome module.

I need to cover this scenario:

* add a job in the queue
* when it comes out of the queue I do an API request
* * if the api says ok I can remove the job from the queue
* * if the api says no the job must return in queue according with the backoff strategy

This is my code when the job is added to the queue:
```javascript
const options = {
    removeOnComplete: true,
    removeOnFail: true,
    backoff: {
      type: 'exponential',
      delay: 2000,
    }
  };
  const data = {...};
  return queue.add(data, options).then(callback);
```

This is the process function:
```javascript
queue.process((job, done) => {
    doApiRequest((err, result) => {
      if (err) return done(new Error(err.message));
      if (!result) {
        done(new Error('NOT READY'));
      } else {
        done(null, result);
      }
    });
});
```

With this code the job as marked in the queue as `stalled` and when the `ttl` expires the process function is not called again.

Where do I am doing mistakes or wrong assumptions in the backoff use?

Best,
Mirko

**Comment by manast** [comment] 2017-09-21 10:47
Not related to the issue you are experiencing, but in order to make retries you should need to specify the ```attempts``` option: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

As long as doApiRequest does not "hang" the event loop, the job should never stall, so it is weird. Can you make a minimal reproducible test?

**Comment by manast** [comment] 2017-10-07 21:34
Closing due to lack of a reproducible test case.

**Closed by manast** 2017-10-07 21:34 UTC
