### ISSUE TITLE
Add job fail when pass repeat.endDate

### ISSUE THREAD

**Issue by nephew92** [OptimalBits/bull#1845] opened 2020-09-03 02:04 UTC
## Description

When pass `endDate` to repeat opts the job is not add and not exception is throw

## Minimal, Working Test code to reproduce the issue.

```javascript
const job1 = await queue.add({
  name: 'job1'
}, {
  repeat: {
    cron: "0 * * * * *",
    startDate: "2020-09-02T22:29:00Z"
  }
})

const job2 = await queue.add({
  name: 'job2'
}, {
  repeat: {
    cron: "0 * * * * *",
    startDate: "2020-09-02T22:29:00Z",
    endDate: "2020-09-03T01:44:37Z"
  }
})

console.log(job1); //looks good, the job was added
console.log(job2); //looks bad, job2 is undefined and the job was not added. No error was throw

```

## Bull version

3.11.0 and 3.18.0

**Comment by manast** [comment] 2021-07-14 07:32
Closing since it works as designed, if ```endDate``` has already passed no job is added to the queue, the above case works if ```endDate``` is a future date.

**Closed by manast** 2021-07-14 07:32 UTC
Labels: work as designed
