### ISSUE TITLE
ReplyError: ERR Error running script user_script:72: too many results to unpack

### ISSUE THREAD

**Issue by npahucki** [OptimalBits/bull#659] opened 2017-08-14 19:32 UTC
I get this error when running in our AWS env which uses an ElasticCache instance for Redis. This error was delivered to the error handler added in `queue.on('error',...)`. After a few of these errors, the queue just silently stops processing jobs. 

Any clues? 

```ReplyError: ERR Error running script (call to f_1eddca842e909a8a091813c195c3f7facb92e55c): @user_script:72: user_script:72: too many results to unpack
19:01:26
at new Command (/var/www/execthread/node_modules/ioredis/lib/command.js:51:8)
at Script.execute (/var/www/execthread/node_modules/ioredis/lib/script.js:22:17)
at Redis.moveUnlockedJobsToWait (/var/www/execthread/node_modules/ioredis/lib/commander.js:164:20)
at Object.scripts.moveUnlockedJobsToWait (/var/www/execthread/node_modules/bull/lib/scripts.js:262:25)
at Queue.moveUnlockedJobsToWait (/var/www/execthread/node_modules/bull/lib/queue.js:734:18)
at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
at tryOnTimeout (timers.js:224:11)
at Command.initPromise (/var/www/execthread/node_modules/ioredis/lib/command.js:63:18)```

I also found this stacktrace *above* the precceding error, but I can't tell if it was related  or part of another error earlier in the log:

```at Timer.listOnTimeout (timers.js:198:5) {}
at JavascriptRedisParser.replyParser.Parser.returnError (/var/www/execthread/node_modules/ioredis/lib/redis/parser.js:24:25)
at JavascriptRedisParser.execute (/var/www/execthread/node_modules/redis-parser/lib/parser.js:572:12)
at Socket.<anonymous> (/var/www/execthread/node_modules/ioredis/lib/redis/event_handler.js:107:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:172:18)
at Socket.Readable.push (_stream_readable.js:130:10)
at TCP.onread (net.js:542:20)```

**Comment by manast** [comment] 2017-08-14 20:03
This could be a duplicate of #645. It is fixed in rc6, would you mind to test if the error is still there?

**Comment by npahucki** [comment] 2017-08-14 20:54
Ok, BTW: I ALSO saw the error in #645, but did not mention it because you addressed it already. I'll try rc6 and let you know.

**Comment by npahucki** [comment] 2017-08-15 15:49
The errors that I was seeing related to #645 are now gone. However, this error that I reported remains, and completely stops the queue from working. I put the full stacktrace down below as I got a good non interleaved one this time. 

One interesting note, is that this does not seem to happen when I run the code locally with a Redis docker container, but seems to happen fairly consistently when run on the development environment in AWS which uses ElastiCache REDIS. That leads me to believe that it may be Redis configuration related (but I don't know what specifically). 

Other Notes: 
  - we have a single job that then creates 12k other jobs. 
  - those 12k jobs are processed with a concurrency of 100.
 - it only seems to get through a little less than 1000 before it starts failing.
 - the last run it got to process 969 jobs, then there appeared 4 instances of the below stack trace in the logs and all queue processing stopped. 

Please let me know what else I can do to help troubleshoot this error (If you have some hunches) as it is critical for us. 



```
{}
at Timer.listOnTimeout (timers.js:198:5) {}
at JavascriptRedisParser.replyParser.Parser.returnError (/var/www/execthread/node_modules/ioredis/lib/redis/parser.js:24:25)
at JavascriptRedisParser.execute (/var/www/execthread/node_modules/redis-parser/lib/parser.js:572:12)
at Socket.<anonymous> (/var/www/execthread/node_modules/ioredis/lib/redis/event_handler.js:107:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:172:18)
at Socket.Readable.push (_stream_readable.js:130:10)
at TCP.onread (net.js:542:20)
From previous event:
at Command.initPromise (/var/www/execthread/node_modules/ioredis/lib/command.js:63:18)
at new Command (/var/www/execthread/node_modules/ioredis/lib/command.js:51:8)
[2017-08-15T15:35:32.662Z] [ERROR] An error has occurred while processing queue 'weeklyListingEmailUser' ReplyError: ERR Error running script (call to f_f47b2e8a05f40e98325905d91edf61cc16d2bb7c): @user_script:72: user_script:72: too many results to unpack
at Redis.moveUnlockedJobsToWait (/var/www/execthread/node_modules/ioredis/lib/commander.js:164:20)
at Object.scripts.moveUnlockedJobsToWait (/var/www/execthread/node_modules/bull/lib/scripts.js:262:25)
at Queue.moveUnlockedJobsToWait (/var/www/execthread/node_modules/bull/lib/queue.js:734:18)
at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
at tryOnTimeout (timers.js:224:11)
at Script.execute (/var/www/execthread/node_modules/ioredis/lib/script.js:22:17)
```

**Comment by manast** [comment] 2017-08-15 17:00
Ok. I will try to figure it out. In the meanwhile two questions:
1) What version of redis are you using in AWS, and is it the same as the one used locally?
2) Can you check a key that ends in :added to see if it empty when the queue has stopped processing jobs?

**Comment by manast** [comment] 2017-08-15 17:03
ok. I can see the error now. You do not need to provide more information.

**Comment by npahucki** [comment] 2017-08-15 17:04
Wonderful, let me know if I can help.

**Comment by manast** [comment] 2017-08-15 17:08
It is going to take some time to fix this one. Maybe you can go back to version rc4, where this error is not present.

**Closed** 2017-08-15 19:05 UTC

**Comment by npahucki** [comment] 2017-08-16 00:33
Thank you for the quick work! I have verified this is fixed in rc7.
