### ISSUE TITLE
Unable to Clean Active Jobs

### ISSUE THREAD

**Issue by bendytree** [OptimalBits/bull#1577] opened 2019-11-30 17:16 UTC
##  Description

I may be misunderstanding `clean`, but `queue.clean(0, 'active')` isn't removing active jobs for me. 

## Minimal, Working Test code to reproduce the issue.

    var queue = new Queue('foo', 'redis://127.0.0.1:6379');
    await queue.clean(0, 'active');
    var jobs = await queue.getActive();
    console.log(`active: ${jobs.length}`); //active: 4

Even if I try to nuke it, they don't go away:

      await queue.pause();
      await queue.empty();
      await queue.clean(0);
      await Promise.all(["completed","wait","active","delayed","failed"].map(async status => {
        await queue.clean(0, status);
      }));

Here's one of the actual jobs that is "active":

    {
      "id": "1575083022-testconsumer-75211a16",
      "name": "__default__",
      "data": {
        "consumerId": "test-consumer",
        "delay": 2000,
        "error": null
      },
      "opts": {
        "jobId": "1575083022-testconsumer-75211a16",
        "attempts": 3,
        "timeout": null,
        "removeOnComplete": true,
        "delay": 0,
        "timestamp": 1575083022241
      },
      "progress": 0,
      "delay": 0,
      "timestamp": 1575083022241,
      "attemptsMade": 2,
      "failedReason": "Unexpected exit code: 7 signal: null",
      "stacktrace": [
        "Error: Unexpected exit code: 7 signal: null\n    at ChildProcess.exitHandler (.../web/node_modules/bull/lib/process/sandbox.js:41:13)\n..."
      ],
      "returnvalue": null,
      "finishedOn": null,
      "processedOn": 1575083028947
    }

## Versions

Bull: 3.12.0
Node: 12.13.0

**Comment by greenreign** [comment] 2019-12-12 13:55
Yes, both clean and empty fail to do anything it seems.

**Comment by sjovanovic** [comment] 2020-06-19 15:53
I can confirm this - can't get rid of an active job.
Example Job that reproduces issue for me (next is not called):

```
function(job, next){
  console.log('here')
}
```

**Comment by TayfunCesur** [comment] 2020-06-25 20:49
Same here, it seems `removeRepeatable` doesn't work. Repeatable job still triggers `process` function and logs the time.
Any ideas?

**package.json**
```
"dependencies": {
    "bull": "^3.14.0"
  }
```

**index.js**
```
const Bull = require('bull');

const myFirstQueue = new Bull('my-first-queue');

const conf = {
    repeat: {
        every: 1000
    }
};

myFirstQueue.add('remove', { foo: 'bar' }, { conf });

myFirstQueue.process(async (job) => {
    console.log(`trying job ${new Date().toISOString()}`);
})

setTimeout(() => {
    myFirstQueue.removeRepeatable('remove', conf).then(() => {
        console.log('SHOULD BE DEAD')
    })
}, 5000);
```

I already looked at this https://github.com/OptimalBits/bull/blob/develop/test/test_repeat.js#L362

**Comment by manast** [comment] 2020-06-25 21:12
The code above is wrong, starting with this line 
```ts
myFirstQueue.add('remove', { foo: 'bar' }, { conf });
```

Since ```conf``` is not a valid option.

**Comment by TayfunCesur** [comment] 2020-06-25 23:11
Hello @manast , thanks for you answer. Actually I didn't understand why it is not valid option because job is working as expected. `conf` has all the needed keys, repeat for `JobOptions` and every for `EveryRepeatOptions`.

Can you give me an insight about the mistake please?

**Comment by DominikSerafin** [comment] 2020-07-16 16:00
@TayfunCesur you've used object property value shorthand in job options, so the repeat key is actually nested inside `conf` object.

This should fix it: `myFirstQueue.add('remove', {foo: 'bar'}, conf);` 

Or this: `myFirstQueue.add('remove', {foo: 'bar'}, {...conf});`

**Comment by TayfunCesur** [comment] 2020-07-17 09:57
@DominikSerafin Thank you so much for your help.
I will try it ASAP :)

**Comment by manast** [comment] 2020-07-17 21:57
Will close this since original code was not correct. Please open new issue with working code if necessary.

**Closed by manast** 2020-07-17 21:57 UTC
