### ISSUE TITLE
Add ability to return promise from a job?

### ISSUE THREAD

**Issue by toddbluhm** [OptimalBits/bull#113] opened 2015-03-27 05:44 UTC
This is very minor, but we use promises in our code a lot (specifically `bluebird`), but now that promises are becoming even more used because they are apart of the EMCA script standard, would it be possible to allow bull jobs to return a promise instead of calling the `done()` callback? This is sort of both a question and a request. Thanks

**Comment by manast** [comment] 2015-03-27 06:42
This is a duplicate of  #21 so I will close this one and we can continue the discussion over there.

**Closed by manast** 2015-03-27 06:42 UTC
