### ISSUE TITLE
Error renewing lock LockError

### ISSUE THREAD

**Issue by NikosEfthias** [OptimalBits/bull#476] opened 2017-03-29 09:29 UTC
`Error renewing lock LockError: Cannot extend lock on resource "bull:58bd19a64df47434492932a0:4:lock" because the lock has already expired.`
i get following error when i run queue with couple of async tasks

**Comment by NikosEfthias** [comment] 2017-03-29 09:36
and also the error event is not fired here

**Comment by manast** [comment] 2017-03-29 09:53
This happens if you are running a long sync task that is keeping the event loop busy. Your alternatives are to divide the task in smaller chunks or use a thread library where the sync code is run.

**Comment by NikosEfthias** [comment] 2017-03-29 10:01
but in the test example i was using timeout which delayed the done callback 3 seconds and i didnt get thie error not its just a couple hundred ms and its giving me this error

**Comment by manast** [comment] 2017-03-29 10:08
A timeout does not keep the event loop busy. But you should at least being able to keep the event busy for 5 seconds (although not recommended), which the the lock default duration. Can you post your process function or a small code example that reproduces the issue isolated?

**Comment by NikosEfthias** [comment] 2017-03-29 10:28
now i noticed when a debugger is attached to the process this error occurs

**Comment by manast** [comment] 2017-03-29 10:30
I wish I could reproduce it.

**Comment by DevBrent** [comment] 2017-04-04 16:12
@NikosEfthias The debugger can be expected to slow down the event loop significantly, but 5 second event loop blocks sound a bit excessive. Perhaps you could delay your calls to start processing jobs by a few seconds while the server is initialized to avoid timeouts on startup.

**Comment by manast** [comment] 2017-05-24 12:43
I will close this now, which seems like even a less issue with last version (3.0.0) of bull with better handling of locks.

**Closed by manast** 2017-05-24 12:43 UTC
