### ISSUE TITLE
Job Ids clash for unnamed repeatable jobs

### ISSUE THREAD

**Issue by tarunbatra** [OptimalBits/bull#727] opened 2017-10-13 10:26 UTC
Repeatable jobs which are not named and have same cron expression have the same jobId `repeat:__default__:<timestamp>`.
In this case the last one to register overrides the previous ones, and only the last job to register executes every time.

**Comment by manast** [comment] 2017-10-13 12:27
This is actually by design. If you have different type of jobs with the same cron job you should probably use a different queue.

**Comment by tarunbatra** [comment] 2017-10-13 12:54
I see. But it's not necessary for the cron expression to be same for this clash. If two different cron expression have a common tick timestamp, (like `* * * * * *` and `*/5 * * * * *` will have same timestamp on the 5th second), won't they collide?

Here's a screenshot for this situation.
<img width="313" alt="screen shot 2017-10-13 at 12 51 41 pm" src="https://user-images.githubusercontent.com/5329230/31547034-5694f458-b015-11e7-8c0f-db2b3e82c98b.png">

The `Job1` stopped getting called once `Job2` gets called, and both have different cron expressions.

**Comment by manast** [comment] 2017-10-24 18:45
Fixed in e380e86c8ab980f25fe81e1dd7a17f2719305d59

**Closed by manast** 2017-10-24 18:45 UTC
Labels: bug
