### ISSUE TITLE
Is the BRPOPLPUSH command executed again after BRPOPLPUSH MaxRetriesPerRequestError?

### ISSUE THREAD

**Issue by oavanruiten** [OptimalBits/bull#1972] opened 2021-02-03 11:03 UTC
## Description

I upgraded my Redis server to use Redis 6. This caused the Redis server to be unavailable for a short period of time.

On the application side, I started getting ECONNREFUSED errors, which is normal.

About 10 seconds after the connection was lost, I got this error:

`BRPOPLPUSH MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.`

A couple of seconds later, the connection was reestablished and the ECONNREFUSED errors stopped.

I noticed that my queue was not processing any jobs after this, so I restarted the app. This resolved it, but I wonder if the BRPOPLPUSH command would be executed again after some time or the queue would be stuck until the next restart?

Also, I learned that the ioRedis' MaxRetriesPerRequest option can be increased, so BRPOPLPUSH (and other commands) are retried more times. This would partially resolve the issue, as BRPOPLPUSH MaxRetriesPerRequestError could still occur if the Redis Server is unavailable for a longer period of time. I can also set MaxRetriesPerRequest to null causing every command to wait forever until the connection is alive again. Is there a recommended approach here for Bull?

#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Start a worker that connects to a Redis Server.

Kill the Redis Server until BRPOPLPUSH MaxRetriesPerRequestError errors show up.

Start Redis Server.

## Bull version
3.20.0

**Comment by oavanruiten** [comment] 2021-02-14 19:22
Hi @manast, do you maybe have an idea? Any help is greatly appreciated!

If my questions are not clear, please let me know so I can reformulate them.

**Comment by manast** [comment] 2021-02-14 21:39
I think this is a duplicate of this issue: https://github.com/OptimalBits/bull/issues/1746
Have you tried with the latest bull version?

**Comment by oavanruiten** [comment] 2021-02-14 21:45
Thanks for your quick reply @manast! I do not believe this is a duplicate of that issue.

In my case I am talking about the Redis server closing the connection, not the client.

**Comment by manast** [comment] 2021-02-15 07:12
Still, I appreciate if you can create a use-case that reproduces the issue with the latest version since I think it will work fine.

**Comment by oavanruiten** [comment] 2021-02-15 08:37
I will create a use-case and get back to you.

**Closed** 2021-07-19 13:56 UTC
Labels: wontfix
