### ISSUE TITLE
removeOnComplete inefficient

### ISSUE THREAD

**Issue by xycloud** [OptimalBits/bull#372] opened 2016-11-10 01:46 UTC
```
co(function* () {
      yield task.add(
          {...},
          {removeOnComplete: true, timeout: 2000, attempts: 2}
      );
}
```

but when job complete, job info still exists in redis

**Comment by bradvogel** [comment] 2016-11-10 01:47
What version of Bull?

**Comment by xycloud** [comment] 2016-11-10 01:50
"bull": "^1.1.0",

**Comment by bradvogel** [comment] 2016-11-10 02:18
I tested and it works for me. Are you sure your job just isn't taking more than 2sec and is being failed? Can you try removing `timeout: 2000`?

**Comment by xycloud** [comment] 2016-11-10 05:54
still inefficient, even only option removeOnComplete remained

**Comment by xycloud** [comment] 2016-11-10 05:59
```
function addJob(queue, job){
  var jobData = job.toData();    //here return undefined
  var toKey = _.bind(queue.toKey, queue);
  return scripts.addJob(queue.client, toKey, job.opts.lifo, jobData);
}
```

I make a debug, and found job is a non-null object, but job.toData() is undefined, is that normal?

**Comment by bradvogel** [comment] 2016-11-10 06:13
Can you post a complete code sample?

**Comment by xycloud** [comment] 2016-11-10 07:30
```
const co = require('co');
const Queue = require('bull');
const task = Queue(task, {
      redis:{
          host:'127.0.0.1',
          port: 6379,
          db: 0,
          opts: {password: 'xxx', keyPrefix:'task'}
      }
});

const message = 'hello, bull';
co(function* () {
     yield task.dingding.add(
          {msgtype: 'text', text: {content: message}},
          {removeOnComplete: true}
      );
});
       
```

**Comment by bradvogel** [comment] 2016-11-10 08:02
What is `task.dingding.add`? Shouldn't that be `task.add()`? Also, what redis command are you running where you see the job still around after completing successfully?

**Comment by xycloud** [comment] 2016-11-10 08:11
@bradvogel typo....    and i see three keys. task:job-mq:id    task:job-mq.completed  task:job-mq:1

**Comment by bradvogel** [comment] 2016-11-10 08:21
ok, and what's in `task:job-mq.completed` ?

**Comment by xycloud** [comment] 2016-11-10 08:22
its a set, where holds the completed task id

**Comment by bradvogel** [comment] 2016-11-10 08:32
ok, I still can't reproduce. Can you push a small node project that reproduces this?

**Comment by xycloud** [comment] 2016-11-10 08:33
what's the redis verison you are using?

**Comment by bradvogel** [comment] 2016-11-10 16:32
v3.2

**Comment by xycloud** [comment] 2016-11-11 02:09
me too, so strange, I quit,  I will take 'job.remove' as a workaround

**Comment by bradvogel** [comment] 2016-11-11 22:10
https://github.com/OptimalBits/bull/issues/376 seems to indicate that that `removeOnComplete` is working for others.

**Comment by rmeja** [comment] 2016-11-14 07:12
as requested by @xycloud , here is my source code : https://github.com/istex/sisyphe/blob/master/src/chain-job-queue.js#L90

**Comment by manast** [comment] 2016-11-22 13:33
Since this issue cannot be reproduced and we have not got more feedback from reporter I will close it.

**Closed by manast** 2016-11-22 13:33 UTC
