### ISSUE TITLE
Add a rate limiter so that the queue does not process more than N jobs per second.

### ISSUE THREAD

**Issue by aniruddha-chakraborty** [OptimalBits/bull#362] opened 2016-10-17 10:26 UTC

**Comment by manast** [comment] 2016-10-17 12:18
Do you mean a setting for the max number of jobs to process per second? (since the minimun is determined by the jobs complexity and the underlying performance of the queue, redis latency, etc).

**Comment by aniruddha-chakraborty** [comment] 2016-10-17 16:33
Yes! exactly i was talking about max number of jobs to process per second. for example my sms api provider strictly said that they will NOT allow more than 10 sms request.

**Comment by manast** [comment] 2016-10-17 17:13
It may be possible to implement a rate limiter following the patterns explained here: http://redis.io/commands/INCR

Also it is important to decide if the rate limiter is per queue or global (using redis it should be possible to make global as well).

**Comment by doublerebel** [comment] 2016-11-14 18:10
Looks like this is a dupe of #329

**Comment by orecus** [comment] 2016-12-14 11:59
This is exactly what I was hoping to se in Bull. I'm working on an application where being able to rate limit (x requests per x seconds) for each of my queues is needed. 

Looking forward to this functionality!

**Comment by ryanmills** [comment] 2017-01-03 04:56
+1 for rate limiting number of jobs being executed concurrently

**Comment by weeco** [comment] 2017-10-13 16:51
@manast I think this issue can be closed or is there something missing?

**Comment by manast** [comment] 2017-10-13 21:33
This is indeed fixed since v3.1.0

**Closed by manast** 2017-10-13 21:33 UTC
Labels: enhancement, PR REQUEST
