### ISSUE TITLE
'global:failed' event error is not an instanceof Error

### ISSUE THREAD

**Issue by petergombos** [OptimalBits/bull#535] opened 2017-05-18 08:25 UTC
Is there a way to get access to the properties of the error returned by the promise on the remote node?

Thanks

**Comment by manast** [comment] 2017-05-18 08:30
the first argument is a job instance, you should be able to check the reason and the stacktrace properties for more info regarding the error.

**Comment by petergombos** [comment] 2017-05-18 08:41
My promise gets rejected with  custom properties attached to the error. I can access them with no problem no the local event handler, but I cant find the original error object when using the global hadlers.

**Comment by manast** [comment] 2017-05-18 10:08
custom properties? We do not serialize the error object, we only care about error message and stacktrace. One alternative is that you put your custom data serialized in the error message.

**Comment by manast** [comment] 2017-05-22 12:24
Will close this issue since it works as designed.

**Closed by manast** 2017-05-22 12:24 UTC

**Comment by petergombos** [comment] 2017-05-22 12:34
Ok, thanks
