### ISSUE TITLE
What's causing EVALSHA failure?

### ISSUE THREAD

**Issue by aknuds1** [OptimalBits/bull#302] opened 2016-05-21 11:35 UTC
On [line 556 of queue.js](https://github.com/OptimalBits/bull/blob/v1.0.0-rc1/lib/queue.js#L556), there is a failure in moving the job to the completed state, due to a Redis failure I am unable to understand:

    { [Error: ERR Error running script (call to f_7bae1666c6fc0e1b7f73920dd0fe76cdfbf9563b): @user_script:3: @user_script: 3: Lua redis() command arguments must be strings or integers ]
      cause: { [Error: ERR Error running script (call to f_7bae1666c6fc0e1b7f73920dd0fe76cdfbf9563b): @user_script:3: @user_script: 3: Lua redis() command arguments must be strings or integers ] command: 'EVALSHA', code: 'ERR' },

What's causing this?

I'm using Redis 3.2.0 installed through Homebrew on OS X localhost.

**Comment by manast** [comment] 2016-05-21 20:48
do you have a minimal code snippet that reproduces this problem?

**Comment by aknuds1** [comment] 2016-05-22 16:38
Sorry, I don't know how to reproduce it. I don't really have the time to try to come up with an example either, I was hoping someone would have insight into what might be happening here. It was just my thinking that with some insight into the workings of the Lua script, it should be possible to understand what's going wrong here.

**Comment by defunctzombie** [comment] 2016-05-26 20:10
It is caused by using redis 3.2 and calling `done()` with no arguments.

**Comment by defunctzombie** [comment] 2016-05-26 20:11
See this issue comment for how I found the workaround https://github.com/OptimalBits/bull/issues/295#issuecomment-218953228

**Comment by manast** [comment] 2016-05-26 20:12
It should be fixed with the commits above.

**Closed by manast** 2016-05-26 20:12 UTC

**Comment by defunctzombie** [comment] 2016-05-26 20:14
@manast 👍 will you be making a release with these fixes soon? Or waiting for larger changes to land?

**Comment by manast** [comment] 2016-05-26 20:15
Waiting for this one: https://github.com/OptimalBits/bull/pull/300

**Comment by manast** [comment] 2016-05-28 08:09
I have made an effort to reproduce this issue but unfortunately I am not able to. If you can provide a step by step instruction to do it I could give it a new try.
Regarding jobs being processed more than once, if the processor is not locking the event loop, I would also need a test case that reproduces it.

**Comment by manast** [comment] 2016-05-28 08:10
Btw, I also made a new release with the latest bugfixes...
