### ISSUE TITLE
Run queue groups [Question]

### ISSUE THREAD

**Issue by Saulolxx** [OptimalBits/bull#1771] opened 2020-06-19 02:48 UTC
I am developing an application that needs to make several HTTP calls asynchronously, and then I need to take the result of those calls and perform a processing. I was wondering if the bull could be useful for this task, how can I process several jobs and then get the result of all to do the processing.

**Comment by manast** [comment] 2020-06-20 16:19
This is a duplicate of this one: https://github.com/OptimalBits/bull/issues/340

**Closed by manast** 2020-06-20 16:19 UTC
