### ISSUE TITLE
Update job data within process

### ISSUE THREAD

**Issue by btmdave** [OptimalBits/bull#168] opened 2015-09-10 21:12 UTC
Is it possible to update job data within process?  We use Kue currently and what we do is update a date in intervals, which basically acts as a heartbeat.  We then have another process that checks all active jobs running and for any where the date has exceeded an unreasonable amount of time, we requeue it.  The case would be if node or server restarted/died in the middle or processes and couldn't be fully handled.

**Comment by btmdave** [comment] 2015-09-10 21:51
Ok so I've been testing this more, it seems it automatically detects jobs that didn't complete or the process was killed and re-starts them.... :+1: 

But, still would have the same question if the data can be updated :)

**Comment by misterjt** [comment] 2015-09-17 19:01
kue cant start executing queue if nodejs was unexpectedly died. This is one of the reasons for me to start using bull, because it can do it!
There is no straight method to update data in both libraries, so i had to just rewrite a whole job.

I join the request to be able to update data while process.

**Comment by manast** [comment] 2015-09-17 19:09
Seems like an interesting use case, I will analyze it and see how feasible it is to implement on the current design.

**Comment by weeco** [comment] 2017-10-18 14:25
@manast Am I missunderstanding this usecase or is this a duplicate of the (nowadays?) implemented "stalled check" ?

**Comment by manast** [comment] 2017-10-18 15:06
Actually this is already implemented: https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#jobupdate
Will close now.

**Closed by manast** 2017-10-18 15:06 UTC
Labels: enhancement, PR REQUEST

**Comment by cefalo-chanchal** [comment] 2020-09-29 13:12
I am trying with 

`hasThisJobInQueue.update({
          delay: delayInMiliseconds < 0 ? 0 : delayInMiliseconds,
        });`

But see the job still has the same delay from the `add`

**Comment by manast** [comment] 2020-09-30 07:55
@cefalo-chanchal but the update only allows you to update the jobs data not the options. In this case you will need to remove the job and re-add it with a different delay.

**Comment by yoferen** [comment] 2021-07-18 05:54
@manast just want to make sure, using job.update to update the job data, if we retry that job so basically it will use the updated data right?

**Comment by manast** [comment] 2021-07-21 09:52
@yoferen yes.

**Comment by adamjjeffery** [comment] 2022-10-03 12:37
@manast ... I have a quick question on the use of the `job.update()` method. I'm trying to update a job's data object using `job.update()`, which works fine if the job is not yet being processed or is not in an active state. 

However, when a job is active, the update method does not update the job. I'm assuming it is frozen once active which makes sense, however, I'm chaining a bunch of processors together, whereby one processor can trigger another processor (but as a single job) and I want to be able to cancel that chain of processors. 

To that end, I'm hoping to update the job's `data` object with a `cancelled: true` property, which I can then act on in the queue's "completed" listener. So if it's been marked as cancelled, I don't bother triggering the next process.

Any ideas or suggestions would be appreciated :)
