### ISSUE TITLE
[BUG] Redis connection leak

### ISSUE THREAD

**Issue by akirilyuk** [OptimalBits/bull#1798] opened 2020-07-13 12:59 UTC
## Description

We have a use case where we have distributed jobs running on multiple pods. Each of the jobs opens a dedicated queue and if the job fails, we want to close the Redis connections. However it seems that this is not working. As a result we are seeing a connection leak on Redis.

The issue can also be reproduced by creating multiple bull queues, then quit them and check the number of redis connections via redis-cli and the [CLIENT_LIST command](https://redis.io/commands/client-list)

## Minimal, Working Test code to reproduce the issue.
```js
const Redis = require('ioredis');
const Queue = require('bull');

const redisHost = 'redis://127.0.0.1:6379';

describe('test redis connection leak', () => {
  it('should not connect client after queue pause and queue close', async () => {
    const defaultRedisClient = new Redis(redisHost);
    const subscriberRedisClient = new Redis(redisHost);

    const newRedis = new Redis(redisHost);

    const redisConnect = jest.spyOn(newRedis, 'connect');
    const redisQuit = jest.spyOn(newRedis, 'quit');

    const createClient = type => {
      switch (type) {
        case 'client':
          console.log('RETURNED CLIENT REDIS');
          return defaultRedisClient;
        case 'subscriber':
          console.log('RETURNED SUBSCRIBER REDIS');
          return subscriberRedisClient;
        default:
          console.log('RETURNED NEW REDIS', type);
          const clientQuit = newRedis.quit.bind(newRedis);
          const clientConnect = newRedis.connect.bind(newRedis);
          newRedis.quit = (...args) => {
            console.log('QUIT CLIENT');
            return clientQuit(...args);
          };
          newRedis.connect = (...args) => {
            console.log('CONNECT CLIENT');
            return clientConnect(...args);
          };
          return newRedis;
      }
    };

    const queue = new Queue('testing', {
      createClient,
      prefix: 'test',
      settings: {
        stalledInterval: 5000,
        maxStalledCount: 9999,
        lockDuration: 30000,
        lockRenewTime: 5000
      }
    });
    queue.process(1, () => {});
    await queue.isReady();
    // pause the queue locally and await jobs to finish
    await queue.pause(true, false);
    // close the queue and underlying redis connection
    await queue.close();

    expect(redisConnect).not.toHaveBeenCalledAfter(redisQuit);
  });
});

```

## Bull version
3.14.0

## Additional information
Node 14.0
Mac OS X 10.14.6

used modules for testing:

 "jest": "26.1.0",
 "jest-extended": "0.11.5",

**Comment by manast** [comment] 2020-07-17 21:57
Thanks will look into this.

**Comment by manast** [comment] 2020-07-18 07:58
Ok. I did study this issue and my conclusion is that it is working as designed. The reason you are seeing a QUIT followed by a connect is because in close we use "local pause" (so you do not need to explicitly use pause in your code above). For blocking connections (such as bclient), we need to break the blocking connection when pausing (otherwise it would try to fetch the next job in the queue), we try first with a clean quit, and then if it does not work we do a force disconnect. In either case we "reconnect" so that the client is ready when you unpause the queue. I agree this could be reworked so that the re-connect can be done only in the case you unpause the queue. 

However, this is not the root of the issue of what you are reporting. The problem is that, since you are providing external redis connections, after closing Bull you will need to close those connections manually too, Bull only closes the connections that it creates itself (the ones it owns).

I hope this makes sense you.

**Closed** 2021-07-13 22:53 UTC
Labels: wontfix, work as designed
