### ISSUE TITLE
Repeatable Job still runs once after removing

### ISSUE THREAD

**Issue by imsergiobernal** [OptimalBits/bull#1680] opened 2020-03-20 20:24 UTC
## Description
If you try to remove a Repeatable Job, I will still run once.

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
```ts
  import bull from 'bull';

  const b = bull('myQueue', { redis: { host: 'redis-bull' } });

  b.process('jobName', async job => {
    console.log('Hello World');
  });

  b.add('jobName', null, { repeat: { cron: '*/10 * * * * *' }, jobId: 'myJobId' })

  setTimeout(async () => {
      const repeatableJob = (await b.getRepeatableJobs()).find(job => job.id === 'myJobId');
      await b.removeRepeatableByKey(repeatableJob.key);
  }, 25000)
```

console.log will print 'Hello World' 3 times instead of 2. Always.

## Bull version
3.12.1

**Comment by manast** [comment] 2020-03-20 22:13
Is this a duplicate of this one? https://github.com/OptimalBits/bull/issues/1675

**Comment by imsergiobernal** [comment] 2020-04-06 10:55
@manast yes it is. I didn't told you anything because I saw that the conversation was forwarded into the #1675 but now It seems to be closed. I'm pending of this issue here then.

**Comment by TayfunCesur** [comment] 2020-06-25 21:02
It seems issue still has not any fix. I am facing same issue with removeRepeatable method also.
Please have a look : https://github.com/OptimalBits/bull/issues/1577#issuecomment-649810226

**Comment by manast** [comment] 2021-02-16 17:04
this was fixed here: https://github.com/OptimalBits/bull/commit/1c76195782fd3b03789c29799ca70859ff559a59
so closing.

**Closed by manast** 2021-02-16 17:04 UTC
