### ISSUE TITLE
job cancellation

### ISSUE THREAD

**Issue by TomKaltz** [OptimalBits/bull#330] opened 2016-08-07 02:43 UTC
So lets say my job spawns another process as in video transcoding.  Is there a way for my job to become aware of removal from the queue while in-flight?  Something similar to the onCancel callback of the cancellation feature in bluebird?

pseudocode...

```
someQueue.process(function(job, done){
  var process = spawn(...)
  process.on('exit',function(code){
    //complete the job with error if bad exit code
  })

  job.onRemove(function(){
    process.kill()
    done(new Error('job cancelled'))
  });
});
```

**Comment by grantcarthew** [comment] 2016-08-18 22:39
Hi @TomKaltz and @manast,

I saw your issue here whilst I was building a Queue base on RethinkDB.
I added this function to my Queue using a property of the error object.

[Read more about it here](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue.process)

Just giving you ideas.

**Comment by doublerebel** [comment] 2016-10-14 00:56
I think this is probably a dupe of #114 ?  I agree cancel/abort is a useful feature, but it's possible to implement through events as noted there.

**Comment by manast** [comment] 2016-11-25 12:27
duplicate #363

**Closed by manast** 2016-11-25 12:27 UTC
Labels: enhancement, PR REQUEST
