### ISSUE TITLE
When call queue.close() bull throws Error: Connection is closed.

### ISSUE THREAD

**Issue by mseld** [OptimalBits/bull#845] opened 2018-01-18 12:22 UTC
## Description
Handling Graceful Shutdown
Bull throws Error after call queue.close()
## Test code to reproduce
```javascript
// just Press CTRL+C after 1 min while component processing messages
const Queue = require('bull');

let queue = ('mail-queue', 'redis://127.0.0.1:6379');

queue.process(function (job, done) {
     // code ...
});

process.on('SIGINT', function () {
    setTimeout(() => {
        queue.close();
    }, 3000);
});

process.on('SIGTERM', function onSigterm() {
    setTimeout(() => {
        queue.close();
    }, 3000);
});
```
## Bull version
3.3.7&8
## Additional information

Error: Connection is closed.
    at Redis.sendCommand (/folders/exe/hlr_charging/node_modules/ioredis/lib/redis.js:558:20)
    at Redis.zrevrange (/folders/exe/hlr_charging/node_modules/ioredis/lib/commander.js:131:17)
    at /folders/exe/hlr_charging/node_modules/bull/lib/getters.js:135:76
    at /folders/exe/hlr_charging/node_modules/bull/lib/getters.js:26:18
    at arrayMap (/folders/exe/hlr_charging/node_modules/lodash/lodash.js:660:23)
    at Function.map (/folders/exe/hlr_charging/node_modules/lodash/lodash.js:9571:14)
    at Queue._commandByType (/folders/exe/hlr_charging/node_modules/bull/lib/getters.js:16:14)
    at Queue.getRanges (/folders/exe/hlr_charging/node_modules/bull/lib/getters.js:124:30)
    at Queue.getJobs (/folders/exe/hlr_charging/node_modules/bull/lib/getters.js:146:17)
    at Queue.getFailed (/folders/exe/hlr_charging/node_modules/bull/lib/getters.js:115:17)
    at Timeout._onTimeout (/folders/exe/hlr_charging/index.js:83:11)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by manast** [comment] 2018-01-18 12:27
Please complete the issue with a code that reproduces the issue.

**Comment by christianbundy** [comment] 2018-03-22 23:53
Looks like OP edited their comment to add repro.

**Comment by christianbundy** [comment] 2018-05-25 18:39
@mseld Which version of Redis were/are you using? We're also getting this on Redis 3.2.

cc: @manast

**Comment by mseld** [comment] 2018-06-02 18:52
redis 3.2

**Comment by christianbundy** [comment] 2018-07-02 17:38
We upgraded to Redis 4 and this problem automatically went away. Seems like this may be specific to Redis 3.2.

**Comment by derN3rd** [comment] 2018-07-20 11:53
Any news on that for Redis 3.2?
We can't upgrade to Redis 4 and our process keeps crashing when calling queue.close()

**Comment by manast** [comment] 2018-07-20 22:31
strange that the workaround works, since ```close()``` already checks if it is closing and it so it does nothing.

**Comment by manast** [comment] 2018-07-20 22:39
Actually I see in the stacktrace that the function that produces the exception is ```getFailed``` -> ```at Queue.getFailed (/folders/exe/hlr_charging/node_modules/bull/lib/getters.js:115:17). 
```
But we never call this function internally, so my guess is that the poster has some timer calling regularly to ```getFailed``` when the queue closes the call fails because the connection to redis has already closed. I could add a check that the queue is not closing before executing the method though.

**Comment by christianbundy** [comment] 2018-07-21 15:07
If it's helpful, here's our stacktrace from Redis 3.2:

```
Unhandled rejection Error: Connection is closed.
    at Redis.sendCommand (/usr/src/app/node_modules/ioredis/lib/redis.js:558:20)
    at Script.execute (/usr/src/app/node_modules/ioredis/lib/script.js:24:26)
    at Redis.isFinished (/usr/src/app/node_modules/ioredis/lib/commander.js:164:20)
    at Object.isFinished (/usr/src/app/node_modules/bull/lib/scripts.js:228:29)
    at Timeout._onTimeout (/usr/src/app/node_modules/bull/lib/job.js:432:19)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

This message repeats indefinitely until you manually close the application.

**Comment by manast** [comment] 2018-07-22 11:40
@christianbundy that is a real bug, I have a fix on its way.

**Comment by manast** [comment] 2018-07-22 11:41
@mseld Regarding your original bug report, as mentioned above, you probably have a time that is calling GetFailed even after the queue has been closed. So this is not a bug in bull.

**Comment by aleccool213** [comment] 2018-10-22 19:05
Think this issue can be closed now?

**Comment by christianbundy** [comment] 2018-10-22 19:29
Yep, feel free to close!

**Closed** 2018-10-23 08:42 UTC
Labels: cannot reproduce, enhancement

**Comment by mgreenw** [comment] 2019-07-17 16:08
Maybe related: I'm getting a weird race condition when closing my Queues from the `jest` `afterAll()` function. It only happens sometimes, and only on a few of the queues. I have tried to trace it in the `close()` .process but haven't made much progress. Here is the stack I'm getting: 

```
console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289
  Unhandled error

console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
Error: Connection is closed.
    at close (node_modules/ioredis/built/redis/event_handler.js:102:25)
    at Socket.<anonymous> (node_modules/ioredis/built/redis/event_handler.js:69:20)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:597:12)
```

Any help/suggestions would be appreciated!

**Comment by gustawdaniel** [comment] 2020-09-07 14:02
I have the same problem

**Comment by talShtark** [comment] 2021-03-07 14:37
me too

**Comment by silverbucket** [comment] 2021-10-10 19:16
> Maybe related: I'm getting a weird race condition when closing my Queues from the `jest` `afterAll()` function. It only happens sometimes, and only on a few of the queues. I have tried to trace it in the `close()` .process but haven't made much progress. Here is the stack I'm getting:
> 
> ```
> console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289
>   Unhandled error
> 
> console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
> Error: Connection is closed.
>     at close (node_modules/ioredis/built/redis/event_handler.js:102:25)
>     at Socket.<anonymous> (node_modules/ioredis/built/redis/event_handler.js:69:20)
>     at Object.onceWrapper (events.js:277:13)
>     at Socket.emit (events.js:189:13)
>     at TCP._handle.close (net.js:597:12)
> ```
> 
> Any help/suggestions would be appreciated!

I'm getting this exact problem as well
