### ISSUE TITLE
Jobs stuck in the active queue 

### ISSUE THREAD

**Issue by amtdevops** [OptimalBits/bull#1766] opened 2020-06-09 10:14 UTC
Hi, 
I am adding running a crawler process to fetch some data from the internet and save it in a file. Everything working for me but when the process executes in a long time, I can see some of my jobs are stuck in an active state, it's not completing/failing. I tried with 'timeout' but didn't work for me. Also noticed when I restart my workers, the jobs in the active state doubled say if it '3000' before, after restart it will be '6000'. I am struck with this, your help much appreciated. 

**One of the example job details** 

```
{
	"id": "48642",
	"name": "__default__",
	"data": {
		"id": "94566",
		"hostname": "t.2b-www.theandaman.com",
		"port": "443",
		"ip": "165.160.15.20",
		"dbdate": "20200608",
		"part": "0",
		"dbDate": "20200608"
	},
	"opts": {
		"removeOnComplete": true,
		"removeOnFail": true,
		"timeout": 300000,
		"attempts": 1,
		"delay": 0,
		"timestamp": 1591694733190
	},
	"progress": 0,
	"delay": 0,
	"timestamp": 1591694733190,
	"attemptsMade": 0,
	"stacktrace": [],
	"returnvalue": null,
	"finishedOn": null,
	"processedOn": 1591695734908
}
```

**Processing job code** 

```
index.crawler.process(config.api.queueConcurrency, async job => {
  try {
    pubSubService.incrementKey('processedJobCount');
    pubSubService.setKey('id', job.data.id);
    return await crawlerController.hostNameCrawler(job.data);
  } catch (error) {
    logger.info(`handle job process errors ${error}`);
    return Promise.resolve({});
  }
});
```
**Process function** 

```
hostNameCrawler: async (data) => {
  return new Promise((resolve, reject) => {
    let errorRes;
    try {
      let {hostname, port, ip, inventory_id} = data;
      let url = utilities.completeUrl(port, hostname);
      if (isValidDomain(hostname)) {
        let tlsData = {
          hostname
        };
        let certificate;
        let hostRes;
        Promise.all([tls.getTls(tlsData), tls.getHostData(url)])
            .then((values) => {
              certificate = values[0];
              hostRes = values[1];
              let $ = cheerio.load(hostRes.data);
              let canonicalUrl = $("link[rel='canonical']").attr("href"); //Get canonical url
              let tlsAltHostnames;
              if (certificate.subjectaltname) {
                tlsAltHostnames = crawlerApi.getAlternateHostnames(certificate.subjectaltname);
              }
              let output = {
                reply_code: hostRes.status,
                hostname: hostname,
                ip: ip,
                port: port,
                url: url,
                request: utilities.rawData(hostRes.config),
                response: hostRes.data
              };
              resolve(output);
            }).catch((error) => {
          errorRes = createError(503, Constant.labelList.unreachableHost + ' ' + url);
          reject(errorRes);
        });
      } else {
        errorRes = createError(503, Constant.labelList.unreachableHost + ' ' + url);
        reject(errorRes);
      }
    } catch (error) {
      errorRes = createError(503, Constant.labelList.unreachableHost);
      reject(errorRes);
    }
  });
},
```
**Errors noticed during processing queue jobs** 

```
q.on('error')
Failed to handle unlocked job in active
Error processing job is:closed 
```

**Comment by manast** [comment] 2020-06-09 15:31
you should not use "done" and return a promise, either use the done callback or return the promise but not both.

**Comment by amtdevops** [comment] 2020-06-10 03:52
Thanks for the response, edited my code, it was copy/paste mistake.  I am only using promise, not using done(). Am I doing anything wrong in implementation?
@manast

**Comment by manast** [comment] 2020-06-10 07:02
You can simplify the code much more. You don't need to create a new wrapper promise since the rest of the code is already promise based, you don't need to try/catch since you can just return a promise and the try/catch is handled by bull, etc. I also recommend you use async/await which will make the code much easier to follow and help you spot the bug.

**Comment by amtdevops** [comment] 2020-06-10 10:35
@manast Thanks for your suggestion. I will try that way. 

Let me know your thoughts about stuck jobs in the 'active' state. Some jobs in the active state are processed (ie 'processedOn' timestamp) on a long time ago but never finished. 

I am running my application with minimum Redis server, so I am running a watcher function in the background to check the number of jobs in Redis, if the job counts increases I will stop the add queue jobs and wait for the job to process. But in this case, active jobs are not finishing and causing issues for me. 

Do I need to implement any background jobs to move these struck jobs to failed state? 
say 
```
let getJobs = await index.crawler.getJobs(status);
for (let value of getJobs) {
//if value.processedOn > 1hr before 
await value.moveToFailed('Stalled jobs clean', true);
}
```

**Comment by manast** [comment] 2020-07-21 08:17
you do not need to do any manually moving of "stalled" jobs. By definition, as soon as they are stalled they are moved back to the "wait" input list. So in your case something else is happening, if you implement my suggestions you may spot easier the bug that is causing this.

**Comment by RodolfoSilva** [comment] 2020-11-01 11:04
@manast 

![image](https://user-images.githubusercontent.com/1703020/97801053-c3850680-1c18-11eb-82a6-1700c7c902af.png)


Has any way to move this jobs to failed state?

**Comment by anhnhatuit** [comment] 2021-07-12 04:19
Hi,
Anyone have experienced to resolve this issue? Can you give me solution?  I'm facing similar this issue. the duration time between added time and process started is too long. It's impact to process speed.

Thanks

**Comment by namli** [comment] 2021-07-25 19:01
To reproduce problem:  Kill\Restart worker process during they open(put to active state) job. I'm my case this happens when pm2(with --watch) or nodemon handle a watcher and restart in case updated source code. 
I find just one solution remove key with job from redis manually and remove a job by id from "bull:updateRssSource:active" as well manually.

**Comment by manast** [comment] 2021-07-25 20:18
@namli that is working as designed. If a worker "dies" while processing a job, the job will be in active state until it is considered stuck and either moved back to wait or failed depending on your options.

**Closed** 2021-07-25 20:19 UTC
Labels: cannot reproduce

**Comment by Vinlock** [comment] 2022-02-08 23:07
I am experiencing a similar issue where jobs are getting stuck in active. We are using the sandbox mode. Jobs will be stuck active until we restart all of the workers.

**Comment by manast** [comment] 2022-02-09 00:31
@Vinlock thats almost guaranteed a faulty processor that is not finishing properly, put logs at the beginning and the end of the processor to really see if the jobs are finalising or not.

**Comment by Vinlock** [comment] 2022-02-09 00:32
> @Vinlock thats almost guaranteed a faulty processor that is not finishing properly, put logs at the beginning and the end of the processor to really see if the jobs are finalising or not.

Will try that! It's odd though. We only are experiencing this in the production environment. Nowhere else with the same queue and processor. 😕. Nonetheless I'm curious as well and am going to wrap things in logs. Thanks! I'll report my findings back.

**Comment by anhnhatuit** [comment] 2022-02-10 02:16
Hello @manast ,

Can I config to move active jobs to waiting or force it as error if it's keeping in this state too long? My issue is still cannot resolve because I could not found the root cause. We need to process > 14M jobs per days and the issue is back after 2-3 days processing and should be restart to resolve the issue.

Thanks,
Nhat

**Comment by manast** [comment] 2022-02-23 07:48
@anhnhatuit you can config a timeout, but it is almost for sure something that hangs in the processor:
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

**Comment by collinscangarella** [comment] 2022-05-03 17:43
I'm having this issue too. Is it possible that there is a bug in bullmq? Like @namli said, this seems to happen when the worker restarts while in the middle of processing a job. Like him, I'm experiencing the issue when running a development server that is hot reloading when changes occur. The code is very simple - they just make an api call and return the promise, things work perfectly fine in unit tests or when the server does not restart. These jobs are stuck in active much longer than they should be - over 24 hours for me. They seem to be stuck indefinitely until I flush redis, which isn't exactly a solution that I can use in production. Shouldn't they emit a 'stalled' event and be moved to 'waiting'? If not, how do I configure them to do so?

**Comment by manast** [comment] 2022-05-04 00:48
@collinscangarella if you are on BullMQ,  do you have a QueueScheduler running at all times? https://docs.bullmq.io/guide/queuescheduler

**Comment by collinscangarella** [comment] 2022-05-06 22:05
I did - but it was configure incorrectly. For those here from google, the 'name' parameter for the queue scheduler is the name of the queue. You need one queue scheduler for each queue.

Thank you.

**Comment by yornaath** [comment] 2022-08-17 14:48
> @collinscangarella if you are on BullMQ, do you have a QueueScheduler running at all times? https://docs.bullmq.io/guide/queuescheduler

> @Vinlock thats almost guaranteed a faulty processor that is not finishing properly, put logs at the beginning and the end of the processor to really see if the jobs are finalising or not.

I am doing both these things and still experience jobs getting stuck on `active`. Logging right before the worker processor function returns, and even when it returns the job isnt removed. Also I have a QueueScheduler running.

**Comment by yornaath** [comment] 2022-08-17 15:02
Additionally I just noticed that when I had some jobs stuck in active but not completing I tried queueing another job and the rest of them followed.

**Comment by piyush8188** [comment] 2023-02-24 11:10
Hi, I am also facing same issue. Also when tried to remove that particular job, it says it is locked. Any suggestions to deal with this?

**Comment by manast** [comment] 2023-02-24 14:32
@piyush8188 there are no know issues regarding job "stucks" in active state. If you can provide a minimal test case (without any external dependency) that shows that this happens, we will look into it in detail.

**Comment by yunyu950908** [comment] 2023-06-25 10:59
same issue here. Bulljs has work fine for my project for several month, but today there's a cron job stuck in active queue for several hours until I clean it manually

`"bull": "^4.10.4"`

**Comment by manast** [comment] 2023-06-25 11:15
@yunyu950908 that's most likely an issue in how the processor is implemented, for instance, the processor is never completing or failing, it just keeps running for ever.

**Comment by anhnhatuit** [comment] 2023-06-25 11:17
Hi @manast , But many users face the same issue. I am facing the same and I must clean my queue by everyday use cron job to resolve the issue

**Comment by manast** [comment] 2023-06-25 14:46
@anhnhatuit many users make mistakes, but it does not mean there is an issue with Bull... if there is, then we just need a piece of code that reproduces it and we for sure will look into it.

**Comment by MrSharpp** [comment] 2023-07-02 19:49
i have this

-  job.js

`const fs = require('fs')

module.exports = async (job) => {
    console.log(job)
    job.log("Working from separated proccess")
    fs.writeFileSync('./hello.txty', "sdfdsf")
    return Promise.resolve({ done: true })
};`

- processor.ts
` const connection = new IORedis(config.REDIS_PORT, {
    host: config.REDIS_HOST,
    password: config.REDIS_PASS,
    connectTimeout: 10000,
  });

  const processFile = path.join(__dirname, 'job.js');
  console.log(processFile);

  const worker = new Worker(config.BULL_QUEUE_NAME, processFile, {
    connection,
  });
  console.log(worker.isRunning());

  worker.on('completed', () => console.log('completed'));
  worker.on('error', () => console.log('err'));
  worker.on('active', () => console.log('active'));
  worker.on('failed', err => console.log(err));
  worker.on('stalled', err => console.log('stalled'));
`

it's doesn't process the job, neither i am getting any console logs

**Comment by manast** [comment] 2023-07-02 21:52
@MrSharpp it is not processing which job? did you add any to the queue?
