### ISSUE TITLE
Reconnection problem

### ISSUE THREAD

**Issue by ks-s-a** [OptimalBits/bull#890] opened 2018-03-16 16:06 UTC
## Description
I create a queue and add tasks to queue every 10 seconds. Use bluebird library to set a delay in a task processor.

The point is - I'm trying to check behavior when redis connection is lost. When I switch off the redis server in prcessors work phase, everything is ok, we finish the task, reconnect and continue task processing.

If I try to switch off the redis server, when there is no tasks in queue, task processing is stop and it doesn't reconnect to the server. The connection is in "end" status.

I need to get any way to establish a connection after redis server was restarted. It's vital for our project.

Logs when I restart redis server on waiting period of the time (non-task processing time):
```
➜  queue git:(master) ✗ node test.js
start task
resolve task!
start task
resolve task!
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: ReplyError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```

Logs when I restart redis server while a task is executing (processing time):
```
➜  queue git:(master) ✗ node test.js
start task
Error in bull queue happend: Error: read ECONNRESET
Error in bull queue happend: Error: read ECONNRESET
Error in bull queue happend: Error: read ECONNRESET
Error in bull queue happend: Error: read ECONNRESET
Error in bull queue happend: Error: read ECONNRESET
Error in bull queue happend: Error: read ECONNRESET
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: ReplyError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
resolve task!
Error in bull queue happend: Error: Missing lock for job 1 failed
start task
resolve task!
start task
resolve task!
```

Look at the end of the copy-paste - new tasks are processing. Everything looks fine unlike the previous example.

## Test code to reproduce
```
const Promise = require('bluebird');
const Queue = require('bull');

const queue = new Queue('test', {
  redis: {
    host: 'localhost',
    port: 6379
  }
});

queue
  .on('error', function (error) {
    console.error(`Error in bull queue happend: ${error}`);
  })
  .on('failed', function (job, error) {
    console.error(`Task was failed with reason: ${error}`);
  });

queue.process('test_task', () => {
  console.log('start task');
  return Promise.delay(5000).then(() => {
    console.log('resolve task!');
  });
});

setInterval(function () {
  queue.add('test_task', {});
}, 10000);
```

## Bull version
bull - 3.3.10, node - v6.10.2

**Comment by manast** [comment] 2018-03-17 16:49
I have not tested further, but the signature to your process function is wrong, you can only have one argument, ```job```, and ```done```, but if you specify the ```done``` callback you need to use it!.
```js
queue.process('test_task', function (job) {
  console.log('start task');
  return Promise.delay(5000).then(() => {
    console.log('resolve task!');
  });
});
```

**Comment by manast** [comment] 2018-03-17 16:51
actually, after fixing the signature I could test that the queue works well even with redis connection interruptions. please verify and close if it works for you.

**Comment by ks-s-a** [comment] 2018-03-19 12:04
@manast Ok. Throw out my small wrappers and use only vanilla library. The result is the same.

Added log outputs and cleaned code snippet.

**Comment by manast** [comment] 2018-03-19 12:32
please try version 3.3.10

**Comment by ks-s-a** [comment] 2018-03-19 13:09
@manast the same story. =(

Fixed version in description.

**Comment by ks-s-a** [comment] 2018-03-21 12:20
@manast Is it reproducible on your machine?

**Comment by manast** [comment] 2018-03-21 12:22
yes I did, seems like a bug in ioredis: seems like it handles incorrectly blocking commands in the event of a disconnection. I did not have time to report it as an issue and/or find a workaround.

**Comment by ks-s-a** [comment] 2018-03-26 09:27
@manast It didn't help me. Absolutely the same result of the test.

**Comment by ks-s-a** [comment] 2018-04-04 09:16
@manast Could you add a link to the ioredis issue? It's important for me to track it. May be if I have some time, I'll try to help them or will investigate the problem.

**Comment by manast** [comment] 2018-04-04 10:02
https://github.com/luin/ioredis/issues/610

**Comment by lincoln-spiteri** [comment] 2018-04-27 13:34
Is there any new info about this. The ticket raised with the ioredis maintainer has not been updated. Are there any known workarounds for this issue?

**Comment by andrelaszlo** [comment] 2018-04-27 13:39
@lincoln-spiteri I tried the workaround suggested in [ioredis#610](https://github.com/luin/ioredis/issues/610#issuecomment-377563044) - disabling the built-in `retryStrategy` and reconnecting manually. It's not great, resending seems broken for example, but it stays connected. I'm also using it with another library, and this library is throwing a few exceptions every time I reconnect...

Also hoping for a better solution soon.

**Comment by luin** [comment] 2018-05-01 03:48
Sorry for the late response. I tested locally using the code provided by @ks-s-a but the result looks correct for me:

```
bull-test ❯ node index.js                                                                                                                  ⏎
start task
resolve task!
start task
resolve task!
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6381
start task
resolve task!
start task
```

I restarted the redis server multiple times at different stages (non-task processing time & processing time) but the result stayed the same. Did I miss something?

Tested with bull 3.3.10 & 3.4.1.

**Comment by kakasal** [comment] 2018-05-31 07:04
```Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)```

**Comment by adogor** [comment] 2018-10-17 14:13
Hi, 

We had a problem of re-connection on our queues, whenever the redis was stopped the "listening" queues could not restart and there was this message each time: 

`ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context`

**We solved it.**

Problem is that when reconnecting ioredis will check if server is ready. This check (https://github.com/luin/ioredis/blob/6dd3730617ece16f874e3ce3e5da0e113ac272d3/lib/redis.js#L413) use the `info` command which is not allowed in the queue context.

So we just had to disable the `enableReadyCheck` option on our configuration to stop this check. After that our config look like :

```
Queue(config.queueName, {
  redis: {
    port: xxx,
    host: xxx,
    maxRetriesPerRequest: null,
    enableReadyCheck: false
  },
});
```

All the queues are now reconnecting has they should do and processing remaining jobs. :+1: 

We hope this option solves some of the connection problems in this thread (maybe not ...), @ks-s-a you might test this ;-)

**Comment by luin** [comment] 2018-10-17 15:03
@adogor Thank you for pointing this out. I'm wondering how to reproduce the error since it works well on my machine with the code provided by @ks-s-a . The error is strange since ioredis should handle the case that ready check is enabled while a `subscribe` command is issued.

**Comment by leonluyong** [comment] 2019-07-04 08:56
@luin tested same code provided by @ks-s-a , still have problem with reconnecting, same output as @ks-s-a provided. Any updates for this issue?

```
Windows 10
bull version 3.10.0
redis: Docker (Redis server v=5.0.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=7983a619928f1f2d)
```
```
D:\Code\nodetest>node test.js 
start task
resolve task!
start task
resolve task!
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: Error: connect ECONNREFUSED 127.0.0.1:6379
Error in bull queue happend: ReplyError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```
no more information even waiting a long time.

**Comment by zyf0330** [comment] 2020-01-15 08:18
If I change `Promise.delay(5000)` to `Promise.delay(1)`, then new job will not be processed anymore.

**Comment by psychonetic** [comment] 2020-10-26 08:32
@adogor Does not work for me.  (3.10.0). 
I get another error: connect ETIMEDOUT when my application tries to add new jobs. Before it was the connection refused error.

Are there any updates on this?

**Comment by manast** [comment] 2020-10-26 10:36
@psychonetic if you have a specific use-case where your problem is reproduced I recommend you to post that, because most issues in this thread are obsolete or user-code specific.

**Comment by gigantedocil** [comment] 2021-05-02 11:10
Hi, I'm having issues in two specific situations:

- If I start the apps that try to create the queue and connect to Redis and Redis is not available at that time, the queues will never work even if Redis becomes available afterwards.
- If I start the apps that try to create the queue and connect to Redis and Redis is available at that time but afterwards Redis becomes unavailable and longer down the line becomes available again, the queues cannot recover from the first disconnect and will not work from that moment onwards.

I have [forked a very simple tutorial](https://github.com/gigantedocil/node-workers-example) from Heroku and updated its dependencies. It is a very simple project that creates a dashboard and creates jobs with the use of Express.js and Bull that can be used to replicate both issues mentioned above.

I run Redis on a Docker container and I shut down the container and then start it again to simulate Redis availability.

I also tried adding the `enableReadyCheck: false` to the Queue constructor as mentioned in this thread but both problems still persist.

**Comment by manast** [comment] 2021-05-03 11:16
@gigantedocil I have test this recently and I could not reproduce any connection issues. Could you just provide some code snippet (not a full repo), that isolates the issue so that I can test it?

**Comment by manast** [comment] 2022-02-23 04:18
@killthekitten backport what exactly?

**Comment by killthekitten** [comment] 2022-02-23 08:07
@manast I mean the default configuration of the ioredis instance, setting  `maxRetriesPerRequest: null, enableReadyCheck: false`.

Sorry for not making it clear.

**Comment by manast** [comment] 2022-02-23 08:32
Check this and let me know if it clarifies this issue: https://docs.bullmq.io/bull/patterns/persistent-connections
AFAIC there is nothing else to do in the library.

**Comment by killthekitten** [comment] 2022-02-23 11:28
My mistake, I wasn't aware of the changes in [this release](https://github.com/OptimalBits/bull/compare/v3.29.3...v4.0.0) and the ones above. Thanks for pointing at the doc and sorry for dragging you here!

**Comment by manast** [comment] 2022-02-23 16:45
Ok. I will close this issue then.

**Closed by manast** 2022-02-23 16:45 UTC
Labels: bug

**Comment by Shahtaj-Khalid** [comment] 2023-06-25 15:42
Hi, I'm observing similar issue, details added here : https://github.com/OptimalBits/bull/issues/2612

In my case, I'm adding jobs in queue directly using `addJobs` lua script, using separate redis client, and jobs are being added properly without any issue. but they are not getting consumed by bull. Once I encounter a EConnReset error in redis queue, consumer starts consuming all the messages again.

Kindly let me know if I'm missing anything, or how to fix this ? It's really important. Thanks.
