### ISSUE TITLE
Null jobs added to queue

### ISSUE THREAD

**Issue by uncledent** [OptimalBits/bull#1657] opened 2020-02-24 08:53 UTC
I am implementing import of application data, user uploads a file with many users, it can be 1000 or 10000. Each user is added to the queue for importing, but many of the jobs created are broken, they are "null" when fetching them.

``` 
let Queue = require('bull');
let testQueue = new Queue('test', {
  redis: {
    port: Number(process.env.REDIS_PORT) || 6380,
    host: process.env.REDISCACHEHOSTNAME,
    password: process.env.REDISCACHEKEY,
  },
});

for (const user of users) {
        await testQueue.isReady();
        await testQueue.add(
          {
            user,
            transactionId,
            tenantId,
          } as UserImportJobData,
          {
            removeOnComplete: true,
            removeOnFail: true,
          },
        );
      } catch (error) {
        console.error(error, 'add-jobs-to-queue');
      }
    }
```

## Current behavior
Add 1350 jobs to the queue -> jobs created, but many of them have __default__ name and no data,  I also cant find those in the REDIS

Here is a screenshot of the paused queue, as you see some jobs are missing data and index (12,50,59). 

<img width="1369" alt="Bildschirmfoto 2020-02-23 um 23 48 58" src="https://user-images.githubusercontent.com/6542981/75121730-17594c00-5697-11ea-9650-5839c191d27d.png">

The more to the list end, the more jobs are corrupt:

<img width="1377" alt="Bildschirmfoto 2020-02-23 um 23 53 09" src="https://user-images.githubusercontent.com/6542981/75121794-acf4db80-5697-11ea-9df2-ff78e80fb427.png">

## Expected behavior
All jobs must be created with data inside and right name

## Environment
   "bull": "^3.13.0",

For Tooling issues:
node v10.16.2
- Platform:  Mac

Any idea to dig into? Maybe the queue is not ready? Or some limit?

Thank you in advance!

## Update 

All 1300 jobs are created normally when setting job data as empty object 

## Update 

This happens always on the paused queue, but also sometimes on the active queue

## Update

So the problem is that if there are a lot of jobs waiting in the queue, then newly added jobs are not added properly, they are nulled. "add" method does not throw in that case, is it meant to be so? How many jobs can be stored and added simultaneously?

**Comment by manast** [comment] 2020-02-26 19:24
this is a very strange error never saw something like this, probably related to the code that adds jobs or the redis instance you are using.

**Comment by DheemanthBhat** [comment] 2020-05-12 17:44
Facing same issue when using named `process`.

**Comment by schwarmco** [comment] 2020-05-15 11:56
i'm currently running into this issue too

occasionally, after running `queue.add('somename', { some: 'data' }, { delay: 10000 }).then(job => console.log(job))`:
* debuglog shows the job has been added `BULL [PID]: Job added [JOBID]`
* the `.then(job => console.log(job))` gives me a perfectly fine Job-Object
* calling `q.getJobs(['delayed'], 0, 10).then(jobs => console.table(jobs))` yields:

```
│   10    │ [Object] │ 'somename' │ [Queue] │ { id: '445239' } │     0     │ 172800000 │ 1589541214331 │     []     │    null     │      0       │ [Function: wrapper] │ '1328' │  undefined   │        │
│   11    │ [Object] │ 'somename' │ [Queue] │ { id: '445233' } │     0     │ 172800000 │ 1589541131654 │     []     │    null     │      0       │ [Function: wrapper] │ '1306' │  undefined   │        │
│   12    │ [Object] │ 'somename' │ [Queue] │ { id: '445234' } │     0     │ 172800000 │ 1589541062599 │     []     │    null     │      0       │ [Function: wrapper] │ '1294' │  undefined   │        │
│   13    │          │            │         │                  │           │           │               │            │             │              │                     │        │              │  null  │
│   14    │          │            │         │                  │           │           │               │            │             │              │                     │        │              │  null  │
│   15    │ [Object] │ 'somename' │ [Queue] │ { id: '445235' } │     0     │ 172800000 │ 1589540779314 │     []     │    null     │      0       │ [Function: wrapper] │ '1289' │  undefined   │        │
│   16    │ [Object] │ 'somename' │ [Queue] │ { id: '445232' } │     0     │ 172800000 │ 1589540686084 │     []     │    null     │      0       │ [Function: wrapper] │ '1286' │  undefined   │        │
│   17    │ [Object] │ 'somename' │ [Queue] │ { id: '445228' } │     0     │ 172800000 │ 1589540648146 │     []     │    null     │      0       │ [Function: wrapper] │ '1284' │  undefined   │        │
```

If you can give me any more options or guidance to debug this, i'd be happy to help

**Comment by matomesc** [comment] 2020-05-26 12:35
I'm having the same issue with `bull@3.13.0`. Some delayed jobs that are retrieved via `queue.getDelayed()` are `null`. All of these delayed jobs were created by a repeatable job.

**Comment by schwarmco** [comment] 2020-05-28 07:49
So, i finally figured it out - and i hope it helps y'all too

**Problem**

Because i haven't used `removeOnComplete` nor `clean()` on a "high-traffic" queue, the `Completed` Jobs piled up and **Redis' hit the `maxmemory` limit**.

The `maxmemory policy` was set to `allkeys-lfu` (drop least frequently used keys), which is a sane setting for Caching but fatal when dealing with jobs. 

This caused the behaviour, that the actual job-key (ex.: bull:somequeue:13) was dropped but the delayed list (ex. bull:somequeue:delayed) still held a reference to that job. So that `getJobs` loaded the list, but not each entry from the least was available anymore.

**Solution**

* Do not run out of memory :D
* Utilize `removeOnComplete` or `clean()` your queues regularly
* Use `noeviction` policy instead to get actual errors from Redis

**Comment by matomesc** [comment] 2020-05-28 13:23
In my case:

- `maxmemory` not hit (usage is ~10%)
- `removeOnComplete` and `removeOnFail` set to 500
- `noeviction` policy

**Comment by supriya-wal** [comment] 2020-10-20 09:15
I am also facing this issue. jobs are stuck in waiting queue and some times in active queue also.I have deleted redis keys using del keyname(bull:someJobQueue:active or bull:someJobQueue:failed). Then i tried again. same thing happening.
I have changed queue name then it works for some time(I know that is not a proper solution, but i tried). Again facing same issue. Someone please suggest fix for this. @manast

**Comment by manast** [comment] 2020-10-20 09:46
@supriya-wal have you checked your maxmemory policy?

**Comment by supriya-wal** [comment] 2020-10-20 09:54
No @manast Could you please tell me how to set maxmemory policy?

**Comment by manast** [comment] 2020-10-20 11:33
@supriya-wal this is a good starting point: https://redis.io/topics/config

**Comment by supriya-wal** [comment] 2020-10-20 11:53
Yeah, i have added maxmemory. but still facing same. please help. @manast
<img width="1440" alt="Screenshot 2020-10-20 at 5 19 21 PM" src="https://user-images.githubusercontent.com/41358730/96582469-f49c3780-12f8-11eb-9ae3-3a88a86cb251.png">

**Comment by supriya-wal** [comment] 2020-10-20 11:55
Yeah i made the changes in redis. but still facing the same. please help @manast 
![Uploading Screenshot 2020-10-20 at 5.25.12 PM.png…]()

**Comment by manast** [comment] 2020-10-20 12:06
@supriya-wal I can only help if I can reproduce the issue... you will need to provide me with some test code that reproduces it.

**Closed** 2021-07-14 09:21 UTC
Labels: cannot reproduce, wontfix
