### ISSUE TITLE
[3.7.0] Higher CPU/Memory consumption

### ISSUE THREAD

**Issue by roychri** [OptimalBits/bull#1226] opened 2019-02-25 15:02 UTC
## Description

We recently upgraded to 3.7.0 but we had to rollback to 3.6.0 due to CPU and Memory consumption growing over time to the point of affecting the event loop so much everything would get deplayed.

![CPU/Memory graph](https://content.screencast.com/users/christian.s.roy/folders/Snagit/media/1e383033-eef6-43d8-86b4-96cdbbca08c8/02.25.2019-09.44.png)

As you can see from this graph, both cpu and memory consumption increased dramatically. The sudden drops is when the services/processes were restarted. Near the end, it was being restarted by a script every 2 hours to keep it somewhat steady. It took me a few days to suspect something else than my own code was doing this.

## Minimal, Working Test code to reproduce the issue.

I have no proof but I suspect one of our main queue is the culprit. It's the one with the most load (and its not that much).
![Arena](https://content.screencast.com/users/christian.s.roy/folders/Snagit/media/d0b3f298-50be-46aa-923a-a8db9ed297a0/02.25.2019-09.47.png)
![Job JSON](https://content.screencast.com/users/christian.s.roy/folders/Snagit/media/8978692b-a583-4aaf-8264-43eb532af6a8/02.25.2019-09.47.png)

```
const queue = new Queue( 'queue_name', redis_url, {
    limiter: {
        max: 99,
        duration: 1000
    }
});
queue.add({
    member_id: event.member_id,
    force: true
}, {
    delay: 5 * 60 * 1000, // 5 minutes
    attempts: 5,
    backoff: {type: 'fixed', delay: 60000}
});
```
## Bull version
3.7.0

## Additional information

The problem starts appearing after ~3-6 hours of working with new jobs appearing every minutes, sometimes every seconds.
I suspect the limiter being the problem. This option is what has been causing the most traffic (see #1222). Whenever I had problems with the slave not being able to keep up is when the limiter was being used by most of my queue. When I disabled the limiter for those that could work fine without it, the Redis slaves stopped lagging like crazy.

**Comment by manast** [comment] 2019-02-25 20:21
thanks for the report. I would guess it is related to the rate limiter. The aim was to actually make it better in 3.7 so that it took less resources, but it seems I failed at that. Will try to implement a better rate limiter that is not based in the delay set, which seems to create a lot of issues.

**Comment by gcox** [comment] 2019-04-07 16:35
Seeing the same behavior. You probably already know what the problem is but here's the limiter options I'm using and my use case:

```typescript
{
  max: 1,
  interval: 3000
}
```
My use case is that I have a recurring job in one queue that will dump a little over 1000 jobs in the rate queue every few hours. The processors for those jobs hit a rate limited API, which is where my limiter options come from. For me, the CPU spike begins about 5-10 minutes in. In redis, the operations/sec metric just keeps increasing to many tens of thousands before I have to kill my app.

Same as the OP, switching to 3.6.0 resolves the issue.

**Comment by manast** [comment] 2019-04-09 16:27
@gcox thanks for the report. When the new rate limiter is in place this should not occour anymore.

**Comment by gcox** [comment] 2019-04-23 20:04
@manast FWIW, in 3.7, I added a `debuglog` call in `scripts.updateDelaySet`. Roughly every 3 seconds, which is the rate limit I've described above, `updateDelaySet` gets called many times. The number of times it's called increases by some amount each time. Eventually, it's being called many thousands of times and this is when the CPU is pegged.

**Comment by manast** [comment] 2019-04-23 20:47
@gcox hopefully this fix will resolve the issue: https://github.com/OptimalBits/bull/pull/1294

**Comment by gcox** [comment] 2019-04-23 23:15
@manast Yes it did!

**Comment by celiolatorraca** [comment] 2019-04-24 12:33
Hi @manast!

Are you planning to release a new version with this fix?
Probably I have the same problem

**Comment by celiolatorraca** [comment] 2019-04-25 11:07
@manast Just for you to know, I tested this bugfix you merged 2 days ago and it seems to be working pretty well since yesterday!

**Comment by manast** [comment] 2019-04-27 09:58
ok, so lets close this now since 3.8.0 has been released

**Closed** 2019-04-27 09:58 UTC
