### ISSUE TITLE
MaxListenersExceededWarning for Queue.process with high concurrency

### ISSUE THREAD

**Issue by lucassimibueno** [OptimalBits/bull#615] opened 2017-07-11 18:22 UTC
This issue is similar to https://github.com/OptimalBits/bull/issues/503. I'm getting lot of warnings like it:

`(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 newjobs listeners added. Use emitter.setMaxListeners() to increase limit`

I guess the problem is the concurrency parameter in the Queue.process. If I set it to a bigger value (~5, I think it depends how many times Queue.process is called) I start to see these warnings. I'm using 3.0.0-rc.4 version.

**Comment by zidsi** [comment] 2017-07-26 13:07
For me it works out to "pre-calculate" total number - sum of of all Queue.process * concurrency... 

and then call queueInstance.setMaxListeners(SumOfProcessCallsMultipliedByConcurrency) before initialization of processors... to avoid this warning.

Looks like every concurrent "processor" has it's own listener (no "dispatcher" listener to distribute work to concurrent workers).

For high concurrent processors dispatcher might lower required listeners. Or every Queue instance could keep record on how many listeners are required and update self with setMaxListeners.

**Comment by manast** [comment] 2017-07-26 13:36
I will investigate this carefully because it seems that this could affect performance adversely.

**Comment by manast** [comment] 2017-08-25 08:34
This issue should not be present in latest release candidate (rc9) so I will close it. Reopen if needed.

**Closed by manast** 2017-08-25 08:34 UTC

**Comment by dskvr** [comment] 2017-09-06 19:05
Any idea when rc9 will be released?

**Comment by manast** [comment] 2017-09-06 20:18
@dskvr Can you provide a test code that reproduces this issue? Observe that this is only a warning, not a real error.

**Comment by makamekm** [comment] 2017-10-13 12:09
I have the same:
```
    const jobs = [];

    const queue = Handler.Queue('test_handler');
    for (let i = 0; i < 50; i++) {
      const job = await queue.add({
        test: 'Hello!' + i
      });
      jobs.push(job.finished());
    }

    await Promise.all(jobs);
```

**Comment by manast** [comment] 2017-10-13 12:26
can you write the complete case where the warning is produced? also I want to remind that this is not an issue, there is no leak, just more than 10 listeners, and can be shut down as explained above.

**Comment by makamekm** [comment] 2017-10-13 12:46
You're welcome)

```
const Queue = require('bull');

const name = 'test';

// Node side
const processQueue = new Queue(name);

processQueue.process(5, async (job, done) => {
    try {
        await new Promise(r => setTimeout(r, 1000));
        done(null, true);
    }
    catch (e) {
        done(e, null);
    }
});

// Server side
const jobs = [];

async function test() {
    const queue = new Queue(name);
    
    for (let i = 0; i < 50; i++) {
        const job = await queue.add({
            test: 'Hello!' + i
        });
        jobs.push(job.finished());
    }
    
    await Promise.all(jobs);
}

test();
```

**Comment by LukaszWiktor** [comment] 2018-09-22 20:03
The issue is still present in bull 3.4.8

**Comment by wlegate** [comment] 2018-10-07 06:09
> The issue is still present in bull 3.4.8

Yep, I just ran into it as well…

**Comment by cgfarmer4** [comment] 2018-10-11 22:53
+3

**Comment by manast** [comment] 2018-10-12 05:55
Increase the amount of listeners. Job.finished requires to setup several listeners so if you call it often you will get the warning. It is not a bug in bull.

**Comment by sibelius** [comment] 2019-06-04 16:15
how can we fix this?

**Comment by popovprodigyai** [comment] 2019-06-04 17:41
Please provide some details on how this can be fixed.

**Comment by manast** [comment] 2019-06-04 19:23
https://nodejs.org/dist/latest-v12.x/docs/api/events.html#events_eventemitter_defaultmaxlisteners

**Comment by popovprodigyai** [comment] 2019-06-04 19:44
Sorry @manast but how it answers the question? Job is called once and is making the basic request to external API, that responds in up to 30 seconds (heavy process on that side). And as noticed, it seems that any job that is long running (20+ seconds) can randomly cause this leak. The same request outside of bull are running with no issues. So it really seems the leak is coming from bull.
We will try to create a case to reproduce it clearly, but you can also try to query any API with response of lets say 1min.

**Comment by manast** [comment] 2019-06-04 21:00
@popovprodigyai this answer the question on how to get rid of the warning which appears if you have defined more listeners than the max 10 that is the default. Some methods in Bull such as "finished" requires extra listeners. So the only way to get rid of the warning is increase the max listeners. We have many tests and none shows this warning. So if you can demonstrate with a reproducible use case that there is indeed a leak I will look into it.

**Comment by nephew92** [comment] 2021-08-10 21:49
same error when I define more than 8 processors to the same queue
```
new Queue(name, { ...opts })
queue.process('p1', processor.p1)
queue.process('p2', processor.p2)
queue.process('p3', processor.p3)
queue.process('p4', processor.p4)
queue.process('p5', processor.p5)
queue.process('p6', processor.p6)
queue.process('p7', processor.p7)
queue.process('p8', processor.p8)
queue.process('p9', processor.p9)
```
bull version: 3.18.0

**Comment by manast** [comment] 2021-08-11 11:53
@nekocode it is not an error, it is a warning (unnecessary in my opinion) coming from NodeJS, you can get rid of it with ```setMaxListeners``` https://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n

**Comment by nephew92** [comment] 2021-08-11 15:55
> @nekocode it is not an error, it is a warning (unnecessary in my opinion) coming from NodeJS, you can get rid of it with `setMaxListeners` https://nodejs.org/dist/latest-v12.x/docs/api/events.html#events_eventemitter_defaultmaxlisteners

use `setMaxListeners` it's not working for me:
```
queue.setMaxListeners(Infinity)
```
even this way the warning keeps.

I've tried these two approach and them was worked:
https://github.com/OptimalBits/bull/issues/1494#issuecomment-538771360
https://github.com/OptimalBits/bull/issues/1494#issue-502934110

but I guess it's not the usual way, speacially because I can not use promise neither timeout on my Queue project:

**Comment by manast** [comment] 2021-08-11 18:25
You should do: ```EventEmitter.defaultMaxListeners(10000)```

**Comment by shahmir2000** [comment] 2023-12-20 13:42
hi @All i also having the same issue in my node js server while using Bull Mq I have fix it by using 
setMaxListeners(0);
where i configure my Redis  like the following 
const Redis = require("ioredis");

const redisConnection = new Redis({
  host: process.env.REDIS_HOST || "localhost",
  port: process.env.REDIS_PORT || your_redis_port ,
  maxRetriesPerRequest: null 
});

redisConnection.setMaxListeners(0);
module.exports = redisConnection;
