### ISSUE TITLE
Missing KEY for job

### ISSUE THREAD

**Issue by Gappa88** [OptimalBits/bull#1341] opened 2019-06-11 08:30 UTC
I have a nodejs code structured as following:
- master script that creates the bull connection to redis and gets jobs.
- the master gets one job at a time, it saves the `done` function in a global variable for future utilization and sends the job to a `child_process` (processor.js)
- the processor execute the job and return the result to the master
- the master execute the previously saved `done` function.

here a snippet of the code:

```
// master.js

const jobid_dones = {};

const cp = require('child_process');
const processor = cp.fork(`${__dirname}/processor.js`, []);

const Bull = require('bull');
let redis_conf = nconf.get("redis_angl:connection_parameters");
const queue = new Bull(nconf.get("redis_angl:prefix"),
  {
    settings: {
      maxStalledCount: 1
    },
    redis: redis_conf
  }
);
queue.process(1, (job, done) => {
    // saving the done function
    jobid_dones[job.id] = done;
    processor.send({ cmd: 'proc', job });
  });

processor.on('message', (obj) => {
  switch (obj.cmd) {
      case 'processed': {
         // complete the job
         jobid_dones[obj.job_id]();
         break;
       }
    }
});
```

```
// processor.js

process.on('message', async (obj) => {
  switch (obj.cmd) {    
    case 'proc': {
     // execute the job
     .....
     // return the result
      process.send({ cmd: 'processed', result});
      break;
    }    
  }
});
```

I could not use the `separate process` provided from bull but this way allows me to reduce the `Missing Lock`/`Stalled` problem but sometimes I got the following error:

`["Error: Missing key for job 472658 finished\n    at Object.finishedErrors (/path/to/scripts/node_modules/bull/lib/scripts.js:180:16)\n    at job.queue.client.moveToFinished.then.result (/path/to/scripts/node_modules/bull/lib/scripts.js:169:23)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"]`

BULL VERSION: 3.10.0
NODEJS VERSION: 8.x

How can I handle this error?
is there any problem with the structure I have created?

thanks

**Comment by manast** [comment] 2019-06-11 17:30
seems like the job has been has been deleted, maybe some other code is deleting the jobs in some circumstances. Why can't you use the built-in process support?

**Comment by Gappa88** [comment] 2019-06-12 07:06
thanks @manast for the response

actually I launch the nodejs program using [PM2](http://pm2.keymetrics.io/) in cluster mode in order to have a bunch of programs running simultaneously eating redis' jobs. 
In theory, using Bull, as Pub/Sub, it prevents that one job will be executed from two different processors in the same moment, right? So I don't understand if there is some kind of race condition that unlocks the job when a processor get it or other issues from other side. Actually, I got these `missing key`s just on few hundred of jobs of about 500k that has been processed during a single night, 'cause of that I'm thinking about some race condition.

I'm not using the built-in process support because I need that the spawned process remains active forever and not be launched for each jobs or after few jobs have been executed, plus other few things.
But if you agree that the structure I have created is correct for the right execution of Bull I feel much safer.

**Comment by marcandrews** [comment] 2020-04-30 02:25
I am also encountering this error and it is extremely rare.

In my case, I am using Bull to manage some long running (hours) tasks as Bull jobs. I am relying on horizontal pod scaling with Kubernetes, so I am not using separate processes or clustering. Each task is unique, but tasks can repeat, so I use the job ID to make sure there is only one job per task and then remove the job upon completion so that it may repeat. 

With respect to recovery when a pods are scaling down or being updated/redeployed, I attempt to gracefully terminate Node by detecting a termination event (such as `SIGTERM`) and then closing the queue with `queue.close()` and then I close the Redis connection, allowing the Node process to terminate and the pod to be scaled down or updated.

With respect to recovery when errors are encountered within a job, I call the job's `done(err)`, and then attempt to retry with with `job.retry()`. If that does not work, I call `job.remove()`. I have another process that checks for missing jobs. This process will detect this removed job as missing and queue it again.

This has been in operation since February and it has been working extremely well. I check the queue every 5 minutes and even when redeploying, I rarely see jobs that are waiting or in an error state.

Just today, I had a job that refused to start and found that the job was still running and had this in it's stacktrace:
```
Error: Missing lock for job 451124342 finished\n    at Object.finishedErrors (/app/node_modules/bull/lib/scripts.js:182:16)\n    at /app/node_modules/bull/lib/scripts.js:169:23\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Since each job is unique, the system thought that the job was still running and did not attempt to start it. Out of thousands of successful jobs, there are only 8 jobs in this state with the same stacktrace.

I am not doing anything special and keep within the safety confines of Bull. I am also using Redis Labs.

Is there anything else I can provide to help?

`bull@3.12.1`
`node-alpine@12-lts`

**Comment by yogesh-webmob** [comment] 2020-12-29 14:06
I have encountered the exact same issue:

Here are few details/observations/debugging steps tried:

- It happens in cluster mode as stated above as well
- Exactly 3rd job is observed to be missed earliest from complete job list when cluster has 2 application workers.
- Jobs are missed regardless of the size. I've tried with 32, 64, 1000 jobs out of which, I got 25 every time.
- I've tried overriding default job ids, still got the same results.

This all was happening because I had `require`d `cluster` module to check which `cluster.worker.id` has got the specific `job.id` to process. I have removed that import for `cluster` and it works fine. Quite strange but it's being reproduced every single time. 

btw @Gappa88 , Did you find any solution or workaround to this?

**Comment by manast** [comment] 2020-12-29 15:17
@yogesh-webmob the most useful would be if you can provide a test case that actually reproduces the issue, then we can take a deep look into it.

**Closed** 2021-07-15 08:01 UTC
Labels: question, wontfix

**Comment by dharmeshds** [comment] 2021-11-09 22:32
To me this was happening when I was marking the job as completed in the Promise 'then()' block. I move it to 'finally()' block and it works without this error.

**Comment by phoebey01** [comment] 2022-03-25 22:25
Hi, I've also recently encountered this issue where a cron job encountered error `["Error: Missing key for job {JOB_ID} finished\n at Object.finishedErrors (/app/node_modules/bull/lib/scripts.js:186:16)\n at /app/node_modules/bull/lib/scripts.js:175:23\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)"]` and has been stalled ever since, where queuing it again on Bull Queue never gets the job to be triggered.

I had to manually delete the JOB_ID in redis to kick off the job again. Any idea of what could have caused this to happen?

**Comment by jnutkis** [comment] 2022-09-30 20:24
I had the exact same issue as phoebey01 when I added the moveToCompleted method to the job handler of my app. I had to also go into the Redis database and remove the key for all jobs of this event. Not sure what I did wrong but leaving this comment for others who may encounter and get stuck resolving.

**Comment by Benjythebee** [comment] 2025-07-12 20:54
I'm facing this issue currently:

bullmq 5.56.4 (and tried downgrading to 5.53.2)

deleting the keys in the Redis db did not help...

```
  await MyQueue.add('myRender', {
      id:job.id,
      s3Key: key,
      userId: user.id,
      created_at: job.created_at,
      filename: safeFileName,
      params: jobParams,
    },
    {
      jobId: job.id
    }
  );
```


```
  const worker = new Worker<JobData>('my-queue', processJob, {
    concurrency: PARALLEL_COUNT,
    autorun: true,
    connection: redisOptions.connection,
    lockDuration: 30000, // 30 seconds
  });
  worker.on('completed', (job) => {
    log.info(`Job ${job.id} completed successfully`);
  });
  worker.on('failed', (job, err) => {
   job && log.error(`Job ${job.id} failed with error: ${err.message}`);
  });

```


I'm not sure it's a redis issue because bull works fine, I get this issue with bullmq

**Comment by manast** [comment] 2025-07-13 09:44
@Benjythebee do you have actual code that reproduces the issue? if so, please open a new issue in the BullMQ repo not here,  and we will look into it.

**Comment by Benjythebee** [comment] 2025-07-21 03:07
Seems like the issue was in the setup, I shouldn't have used `keyPrefix` in the redis connection
