### ISSUE TITLE
Change schedule for the repeatable job

### ISSUE THREAD

**Issue by tomas-berg** [OptimalBits/bull#1675] opened 2020-03-13 07:20 UTC
Team,

Here is the real world scenario:
We have one queue and and repeatable cron-like job, for example, repeat every `5 seconds`:

```javascript
    await queue.add({}, {
        removeOnComplete: true,
        removeOnFail: true,
        repeat: {
            every: 5000
        }
    });
```

Let's pretend we need to restart our app and change repeat for 10 seconds.
It suggested to remove repeatable jobs by `getRepeatableJobs()` and remove them by `removeRepeatableByKey()`.

But in fact, previously scheduled job will still be executed one time before the new job schedule will take place.

Nor `queue.clean(0)` or `queue.empty()` doesn't help.

It's definitely very confusing and NOT expected scenario.

Is there a right way to do that?

**Comment by manast** [comment] 2020-03-13 08:50
If the previous repeatable job was removed, then it should not schedule new jobs after that, if so it is a bug. Can you prepare a minimal case that reproduces the issue?

**Comment by tomas-berg** [comment] 2020-03-13 10:23
@manast 
Thanks for the quick reply.

I've put some minimal one-file sample [here](https://github.com/tomas-berg/bull-testing)

If you check the code below and run it first time, then stop and change job's data and repeat option and run it second time - the first job will be executed once again. How to achieve case when previously scheduled job will not be executed?

```
'use strict';

const Bull = require('bull');

const proc = function (job, done) {
    try {
        const { data } = job;
        console.log(`Job data: [${data.payload}]`);
        done();
    } catch (e) {
        console.error(e.message);
        done(e);
    }
};

const queue = new Bull('test', {
    redis: {
        host: '0.0.0.0',
        port: 6379,
        db: 0,
        password: 'secret'
    }
});

(async () => {
    const repeatable = await queue.getRepeatableJobs();
            
    repeatable.forEach(async (job) => {
        await queue.removeRepeatableByKey(job.key);
    });

    queue.process(proc);
    await queue.add({
        payload: 'j0' // <<< change it next run
    }, {
        removeOnComplete: true,
        removeOnFail: true,
        repeat: {
            every: 1000 // <<< change it next run
        }
    });
})();
```
Thanks a lot.

**Comment by manast** [comment] 2020-03-14 16:31
not sure if it affects the outcome, but in the code above it will add the repeatable job BEFORE you have removed the old jobs. Try to use Promise.all and map instead:
```js
    await Promise.all(repeatable.map((job) => queue.removeRepeatableByKey(job.key)));
```

**Comment by tomas-berg** [comment] 2020-03-16 10:24
@manast 
Just tried. The result is just the same. After second run - the old scheduled job executes one time.

**Comment by manast** [comment] 2020-03-17 21:53
can you post the updated code?

**Comment by tomas-berg** [comment] 2020-03-20 09:05
@manast 
sure, pleasee check [latest sample](https://github.com/tomas-berg/bull-testing)

**Comment by manast** [comment] 2020-03-20 21:42
this happens because even though you deleted the repeatable job, the next programmed job is still in the delay queue waiting to be executed, a quickaround would be to clean the delayed jobs after removing the repeatable job, if you change the code to this one it will work:
```js
(async () => {
    const repeatable = await queue.getRepeatableJobs();
            
    await Promise.all(repeatable.map((job) => queue.removeRepeatableByKey(job.key)));
    
    // repeatable.forEach(async (job) => {
    //     await queue.removeRepeatableByKey(job.key);
    // });

    await queue.clean(0, 'delayed');

    queue.process(proc);
    await queue.add({
        payload: 'j0' // <<< change it next run
    }, {
        removeOnComplete: true,
        removeOnFail: true,
        repeat: {
            every: 1000 // <<< change it next run
        }
    });
})();
```
but yes, it may be an overlook of my side and I should remove the delayed job associated to the repeatable job when removing the repeatable job. Will mark this a bug.

**Comment by imsergiobernal** [comment] 2020-03-23 08:51
> this happens because even though you deleted the repeatable job, the next programmed job is still in the delay queue waiting to be executed, a quickaround would be to clean the delayed jobs after removing the repeatable job, if you change the code to this one it will work:
> 
> ```js
> (async () => {
>     const repeatable = await queue.getRepeatableJobs();
>             
>     await Promise.all(repeatable.map((job) => queue.removeRepeatableByKey(job.key)));
>     
>     // repeatable.forEach(async (job) => {
>     //     await queue.removeRepeatableByKey(job.key);
>     // });
> 
>     await queue.clean(0, 'delayed');
> 
>     queue.process(proc);
>     await queue.add({
>         payload: 'j0' // <<< change it next run
>     }, {
>         removeOnComplete: true,
>         removeOnFail: true,
>         repeat: {
>             every: 1000 // <<< change it next run
>         }
>     });
> })();
> ```
> 
> but yes, it may be an overlook from my side and I should remove the delayed job associated to the repeatable job when removing the repeatable job. Will mark this a bug.
> 2

What if I want to remove just the delayed job from an specific repeatable job?

**Comment by sundowndev** [comment] 2020-07-21 12:32
@imsergiobernal We have the same issue and ended up with this solution :

- Create the job without repeat option
```js
await queue.add({ ... });
```
- Inside the job, create a duplicate job in the queue with a delay only when needed
```js
await job.queue.add(job.data, {
    delay: 5000, // clone this job and execute it in 5 seconds
});
```
Just `return` to prevent another job to be created. So we can stop repeating the job as needed.

This might be an anti-pattern, but that's the only solution I've come across this far. We needed to prevent *this* particular job from repeating again, some all jobs from the queue.

**Comment by manast** [comment] 2021-02-16 17:05
This issue was resolved here https://github.com/OptimalBits/bull/commit/1c76195782fd3b03789c29799ca70859ff559a59
so closing...

**Closed by manast** 2021-02-16 17:05 UTC
Labels: PR REQUEST, bug

**Comment by aditya-rewari-cb** [comment] 2021-09-13 02:20
@manast Is it required to change the data payload everytime

``
await queue.add({
        payload: 'j0' // <<< change it next run
    }
``

**Comment by aditya-rewari** [comment] 2021-09-16 00:11
Only cleaning the `DELAYED` queue worked for me.

`    
        queue.clean(0, 'delayed'); // clean only delayed queue
        await queue.add({}, {
        removeOnComplete: true,
        removeOnFail: true,
        repeat: {
            every: 5000
        }
    });
`

@manast My concern is that can this cause some bug condition.. which I am not able to anticipate !
Kindly suggest. Thanks!

**Comment by manast** [comment] 2021-09-16 01:23
There is a small possible hazard since the process could potentially crash between cleaning delayed and adding the new job.

**Comment by andreaspapazois** [comment] 2023-12-21 19:58
@manast I believe there is an issue when a repeatable is removed and after a new repeatable with exactly the same parameters is added.
It seems that the add operation considers that it is a duplicate and it does not add the delayed job, causing no further action.
