### ISSUE TITLE
Bug : Priority not working - when moving the jobs to pending state and adding jobs inbetwen

### ISSUE THREAD

**Issue by sharmilasudhakar** [OptimalBits/bull#922] opened 2018-04-27 06:50 UTC
**Description**
Priority is not working when all the jobs in the queue are moved to the pending state and at the same time 2 jobs are in the Active state. If I pause and resume the queue it gets collapsed.

**Test code to reproduce** 
```
var redisAdapter = require('redis');
var redicli = redisAdapter.createClient('redis://127.0.0.1:6379');
var Queue = require('bull');
var async = require('async');
var queue = new Queue("qname", 'redis://127.0.0.1:6379');
function add() {
    for (var i = 1; i < 4; i++) {
        queue.add({ id: i }, { priority: i, jobId: i });
        console.log("Added " + i);
        if (i == 3) {
            resume();
        }
    }
}
function addtwomoreinbetween() {
    pause();
    queue.add({ id: 4 }, { priority: 4, jobId: 4 });
    console.log("Added 4");
    queue.add({ id: 5 }, { priority: 5, jobId: 5 });
    console.log("Added 5");
}
queue.process(function (job, jobDone) {
    console.log("job started : " + job.data.id);
    setTimeout(jobDone, 1000);
});
function resume() {
    queue.resume().then(function () {
        console.log('queue is resumed now.');
    });
}
function pause() {
    queue.pause().then(function () {
        console.log('queue is paused now.');

    });
}
function getjobsbyqueuename() {
    console.log("-----------For the queue to Restart - Get the jobs once all jobs arecompleted--------------");
    jobs = [];
    var firstPartOfKey = "bull:qname:*";
    var jobs = [];
    s = [];
    redicli.keys(firstPartOfKey, function (err, keys) {
        if (err) return console.log(err);
        if (keys) {
            async.map(keys, function (key, cb) {
                redicli.hkeys(key, function (err, data) {
                    if (err) {
                        return cb(err);
                    } else {
                        s.push(key);
                        redicli.hgetall(key, function (err, data) {
                            if (err) {
                            } else {
                                var datas = JSON.parse(data.opts);
                                jobs.push(datas.jobId);
                                if (jobs.length == s.length) {
                                    makePendingByQueuename(jobs);
                                }
                            }
                        });
                    }
                });
            });
        }
    });
}
function makePendingByQueuename(arrid) {
    var multi = [];
    var firstPartOfKey = "bull:qname:";
    for (var id in arrid) {
        multi.push(["lrem", firstPartOfKey + "active", 0, arrid[id]]);
        multi.push(["lrem", firstPartOfKey + "wait", 0, arrid[id]]);
        multi.push(["zrem", firstPartOfKey + "completed", arrid[id]]);
        multi.push(["zrem", firstPartOfKey + "failed", arrid[id]]);
        multi.push(["zrem", firstPartOfKey + "delayed", arrid[id]]);
        //Add to pending
        multi.push(["rpush", firstPartOfKey + "wait", arrid[id]]);

    }
    redicli.multi(multi).exec(function (err, data) {
        if (err) {
        } else {
            pause();
            console.log("All jobs in the queue made pending and the jobsa started automatically and couldn't pause it");
        }
    });
}
pause();
add();
setTimeout(addtwomoreinbetween, 3000);
setTimeout(resume, 5000);
setTimeout(getjobsbyqueuename, 8000)
setTimeout(resume, 9000)
```

** Test Code Result **
Added 1
Added 2
Added 3
queue is paused now.
queue is resumed now.
job started : 1
job started : 2
job started : 3
Added 4
Added 5
queue is paused now.
queue is resumed now.
job started : 4
job started : 5
-----------For the queue to Restart - Get the jobs once all jobs arecompleted--------------
All jobs in the queue made pending and the jobsa started automatically and couldn't pause it
queue is paused now.
job started : 3
queue is resumed now.
job started : 1
job started : 4
job started : 5
job started : 2

**Bull version** Latest

**Additional information**
The following are the issues I face,
1.Jobs need to be started based on the priority at any case.
2.If I add the jobs in between the queue it should play one after the other only based on the priority

Please help me to sort out these issues.

**Comment by manast** [comment] 2018-04-27 21:12
I am not sure I fully understand your issue but ```makePendingByQueuename``` is just pushing jobs to the wait list, whereas in bull, they are inserted in the wait list taking into consideration their priorities. Btw, I would recommend you that you write the code using async/await, it will be both much clearer and also more stable, you are currently not waiting many promises to resolve, but assume that they are executed in order, that it is not guaranteed.

**Comment by manast** [comment] 2018-04-30 14:17
Can't you just re-add all the jobs again?

**Comment by sharmilasudhakar** [comment] 2018-05-02 04:57
So every time i need to store the job datas some where and re-add the jobs to the queue. Right?
If that is the solution means can you please tell is there any event to find when a queue completely processed ? Because I not only need to restart the queue i need to loop the queue automatically once fully processed.

**Comment by manast** [comment] 2018-05-02 20:39
You can use the "drained" event, that for some reason it is not documented :/

**Comment by sharmilasudhakar** [comment] 2018-05-04 10:04
Thank you the 'drained' event worked. Can I add a job as pending/wait instead of pausing the queue and adding it?
I need to add a job as pending in between a processing queue.

**Comment by manast** [comment] 2018-05-05 13:33
you cannot pause a job that is being processed.

**Comment by sharmilasudhakar** [comment] 2018-05-07 05:42
Is there any other way to stop a processing job?

**Comment by sharmilasudhakar** [comment] 2018-05-07 10:29
Hi, I re-added the jobs using below function is not processing based on the priority.

```
function readd(){
    queue = new Queue("qname", 'redis://127.0.0.1:6379');
    var types= ['waiting', 'active', 'completed', 'failed', 'delayed', 'paused'];
    queue.getJobs(types).then(function (jobs) {		
		queue.clean(2000).then(function(){
			for(var data1 in jobs)
			{
                          queue.add(jobs[data1].data, {
                          jobId: jobs[data1].data.id,
                          priority: jobs[data1].data.priority
			    })
			}
		})
	}).catch(function (error) {
	});
}
```

Please help me on this.

**Comment by manast** [comment] 2018-05-14 14:57
I am closing this since it seems to be a support question more than an issue with bull. Create new reproducible issue if needed.

**Closed by manast** 2018-05-14 14:57 UTC
Labels: question
