### ISSUE TITLE
Delayed jobs are getting removed from the queue

### ISSUE THREAD

**Issue by ganesh-sg** [OptimalBits/bull#1502] opened 2019-10-13 11:41 UTC
## Description
I am using bull for long running jobs. I am using a pattern in which I have a scheduler, fetcher and processor. 
Scheduler is responsible for scheduling repeating jobs. Fetcher processes the repeating jobs. It also adds processing jobs to the queue. The processor finishes the job by picking up processing jobs from the queue.

I am observing that, after a while, the scheduled jobs are no longer added to the queue. That is, I don't see them in the delayed queue any more. I was using AWS ElastiCache for redis. There were no cache evictions occurred in ElastiCache

The code below is the similar to the one I have in my project. Do you see anything wrong with the way I am using bull or am I encountering an issue with bull?

## Minimal, Working Test code to reproduce the issue.
_job-queue.js_
```
const JobQueue = require('bull');
const Redis = require('ioredis');
const {REDIS_PORT, REDIS_HOST} = process.env;
const REDIS_URL = `redis://${REDIS_HOST}:${REDIS_PORT}`;
const client = new Redis(REDIS_URL);
const subscriber = new Redis(REDIS_URL);

const opts = {
    createClient: function (type) {
        switch (type) {
            case 'client':
                return client;
            case 'subscriber':
                return subscriber;
            default:
                return new Redis(REDIS_URL);
        }
    },
    limiter: {
        max: 1,
        duration: 100,
        bounceBack: false
    }
};

let myScheduler = new JobQueue('MyScheduler', opts);
let myProcessor = new JobQueue('MyProcessor', opts);

myScheduler.addProcessingJob = (data) => {
    console.log("Adding to processing queue", data);
    myProcessor.add("processor", data, {removeOnComplete: true});
};
module.exports.myScheduler = myScheduler;
module.exports.myProcessor = myProcessor;
```
_scheduler.js_
```
const {myScheduler} = require('./job-queue');

async function configure() {
    await myScheduler.removeRepeatable("first", {cron: '*/15 * * * * *'}).catch(console.error);
    await myScheduler.removeRepeatable("second", {cron: '*/30 * * * * *'}).catch(console.error);

    await myScheduler.add("first", {}, {repeat: {cron: '*/15 * * * * *'}, removeOnComplete: true});
    await myScheduler.add("second", {}, {repeat: {cron: '*/30 * * * * *'}, removeOnComplete: true});
}
configure();

```

_fetcher-configurator.js_
```
const {myScheduler} = require('./job-queue');
myScheduler.process("*", __dirname+"/fetcher");

```
_fetcher.js_
```
const first = require('./jobs/first-job');
const second = require('./jobs/second-job');

module.exports = function (job) {
    switch (job.name) {
        case "first":
            return first();
        default:
            return second();
    }
};

```
_processor-configurator.js_
```
const {myProcessor} = require('./job-queue');
myProcessor.process("*", __dirname + "/processor");
```
_processor.js_
```
const moment = require('moment');
module.exports = function (job) {
    console.log(`Processor for '${job.data.name}' ${moment().format("YYYY-MM-DD hh:mm:ss")}`);
    return Promise.resolve()
};
```
_first-job.js_
```
const {myScheduler} = require('../job-queue');
async function job() {
    console.log("First job....");
    myScheduler.addProcessingJob({'name': 'Email from first job'});
}
module.exports = job;

```
There are 3 processes here 
1. scheduler
2. fetcher-configurator
3. processor-configurator
## Bull version
3.11.0

**Comment by stansv** [comment] 2019-10-14 11:41
HI! It will require some time to sort this out..

**Comment by osayfun** [comment] 2020-03-31 14:28
Experiencing the same issue. My code is as simple as it its:
````javascript
    const queue = new Bull('TempDeletion', { redis: { host } });
    const length = await queue.count();
    if (length != 1) {
      await queue.add(
        'Empty /var/uploads/tmp',
        { path: `${config.upload.path}tmp` },
        { repeat: { cron: '15 01 * * *' } }
      );
    }
    return;
```
But the queue stays empty!

**Comment by npahucki** [comment] 2021-04-07 21:27
Any updates on this? We have the same issue, after some time running, delayed jobs randomly disappear. We are also using Redis on ElasticCache. I don't see any evictions either.

**Comment by manast** [comment] 2021-04-07 21:32
@npahucki as long as the issue cannot be reproduced there is no possibility for us to make any progress in resolving it...

**Comment by chongma** [comment] 2021-06-07 11:03
My delayed jobs are disappearing also.  I am watching them with bull dashboard.  i am trying to delay for 24 hours.  none of my long delay jobs ever get completed.  do i need to set a max timeout somewhere?

items also disappear from the completed queue which i am not as worried about.

**Comment by chongma** [comment] 2021-06-07 11:45
never mind i think my redis installation is having problems with directory permissions

**Comment by manast** [comment] 2021-06-07 18:09
@chongma I hope you have set ```maxmemory-policy: noeviction``` otherwise all kind of strange issues can happen since redis will delete keys when the memory starts to become full.

**Comment by chongma** [comment] 2021-06-08 07:41
@manast thank you. i just ran `redis-cli info` inside the docker container and `maxmemory_policy:noeviction` seems to be the default. 

my problem was that for some reason redis was looking for the database in `/etc`.  a lot of comments said that redis can get hacked by a bot.  i didn't need to expose the port outside docker so i closed the port and redeployed the container and now it is looking back in `/data` and finding the database.  hopefully the issue is fixed.  not sure how the container could be hacked as that port was never exposed onto the internet

**Closed** 2021-08-14 08:37 UTC
Labels: wontfix, cannot reproduce
