### ISSUE TITLE
rate limiting?

### ISSUE THREAD

**Issue by afrozl** [OptimalBits/bull#329] opened 2016-08-04 18:08 UTC
Is it possible to limit a job (keyed on an argument) to only run x times a period? does bull have a plugin framework so commonly used functions can be shared across jobs?

**Comment by zoell** [comment] 2016-08-22 23:28
I am also interested in this. Have you ever find a solution with bull or any other library?

**Comment by bradvogel** [comment] 2016-08-22 23:37
Have you seen https://github.com/OptimalBits/bull/pull/335 that just got merged? You can give the job a unique key and a delay, so if you add a job with that same id that is currently queued, it won't do anything. So basically throttling. cc @pricj004

**Comment by manast** [comment] 2016-11-25 12:25
Closing due to be a duplicate of #362

**Closed by manast** 2016-11-25 12:25 UTC
Labels: enhancement, PR REQUEST
