### ISSUE TITLE
Share redis client across queues created by bull() calls?

### ISSUE THREAD

**Issue by redroot** [OptimalBits/bull#246] opened 2016-02-17 16:29 UTC
Hi, I'm not sure if this issue has already been addressed so I'm tentatively opening a new issue, please advise me if I've missed an already open issue.

I noticed that bull tends to create a new redis client everytime you call `bull()`, rather than sharing a pre-existing client (memoizing it maybe). Background: We're using bull on Heroku, using Heroku's Redis addon, meaning we have a limited number of connections so the more worker we want to add, the more expensive the plan we have to pay for.

Is this a design decision or something that I can work on improving in a PR?

You can recreate it locally by running the following node code which is lifted from my codebase, and then running `CLIENT LIST` in `redis-cli`

```
var bull = require('bull');
var _ = require('underscore');

var createQueue = function(name) {
  return bull(name, 6379, '127.0.0.1');
};


var queueProcessingMap = [
  {
    queueName: 'url-download',
    queueProcessor: function() { },
    concurrency: 5
  },
  {
    queueName: 'file-creation',
    queueProcessor: function() { },
    concurrency: 3
  },
  {
    queueName: 'pdf-process',
    queueProcessor: function() { },
    concurrency: 5
  },
];

// use to shutdown all queues on SIGTERM later
var queueList = [];

_.each(queueProcessingMap, function(item) {
  _.times(item.concurrency, function(i) {
    console.log("Starting " + item.queueName + " worker " + (i + 1) + " of " + item.concurrency);
    var queue = createQueue(item.queueName);
    queue.process(item.queueProcessor);
    // queue.on() listeners ...
    queueList.push(queue);
  });
});

// call close of all queue workers then exit process
process.once('SIGTERM', function(sig) {
  logger.info('Closing all queues before killing worker ...');
  var closePromises = [];
  _.each(queueList, function(queue) {
    closePromises.push(queue.close());
  });
  Promise
    .all(closePromises)
    .then(function() {
      logger.info("All queues closed, killing worker");
      process.exit(0);
    }).catch(function(err) {
      logger.info("Error closing queues, killing worker");
      logger.error(err);
      process.exit(0);
    });
});
```

Output from the above code:

```
$ node test.js 
Starting url-download worker 1 of 5
Starting url-download worker 2 of 5
Starting url-download worker 3 of 5
Starting url-download worker 4 of 5
Starting url-download worker 5 of 5
Starting file-creation worker 1 of 3
Starting file-creation worker 2 of 3
Starting file-creation worker 3 of 3
Starting pdf-process worker 1 of 5
Starting pdf-process worker 2 of 5
Starting pdf-process worker 3 of 5
Starting pdf-process worker 4 of 5
Starting pdf-process worker 5 of 5
```

Output from `CLIENT LIST` in `redis-cli`:

```
127.0.0.1:6379> client list
id=447 addr=127.0.0.1:58140 fd=44 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=448 addr=127.0.0.1:58141 fd=45 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=409 addr=127.0.0.1:55512 fd=6 name= age=6907 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
id=410 addr=127.0.0.1:58103 fd=7 name= age=4 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=411 addr=127.0.0.1:58104 fd=8 name= age=4 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=412 addr=127.0.0.1:58105 fd=9 name= age=4 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=413 addr=127.0.0.1:58106 fd=10 name= age=4 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=404 addr=127.0.0.1:54771 fd=5 name= age=91304 idle=91255 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=keys
id=414 addr=127.0.0.1:58107 fd=11 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=415 addr=127.0.0.1:58108 fd=12 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=416 addr=127.0.0.1:58109 fd=13 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=417 addr=127.0.0.1:58110 fd=14 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=418 addr=127.0.0.1:58111 fd=15 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=419 addr=127.0.0.1:58112 fd=16 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=420 addr=127.0.0.1:58113 fd=17 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=421 addr=127.0.0.1:58114 fd=18 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=422 addr=127.0.0.1:58115 fd=19 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=423 addr=127.0.0.1:58116 fd=20 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=424 addr=127.0.0.1:58117 fd=21 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=425 addr=127.0.0.1:58118 fd=22 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=426 addr=127.0.0.1:58119 fd=23 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=427 addr=127.0.0.1:58120 fd=24 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=428 addr=127.0.0.1:58121 fd=25 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=429 addr=127.0.0.1:58122 fd=26 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=430 addr=127.0.0.1:58123 fd=27 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=431 addr=127.0.0.1:58124 fd=28 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=432 addr=127.0.0.1:58125 fd=29 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=433 addr=127.0.0.1:58126 fd=30 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=434 addr=127.0.0.1:58127 fd=31 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=435 addr=127.0.0.1:58128 fd=32 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=436 addr=127.0.0.1:58129 fd=33 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=437 addr=127.0.0.1:58130 fd=34 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=438 addr=127.0.0.1:58131 fd=35 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=439 addr=127.0.0.1:58132 fd=36 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=440 addr=127.0.0.1:58133 fd=37 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=441 addr=127.0.0.1:58134 fd=38 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=442 addr=127.0.0.1:58135 fd=39 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=443 addr=127.0.0.1:58136 fd=40 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
id=444 addr=127.0.0.1:58137 fd=41 name= age=3 idle=3 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpoplpush
id=445 addr=127.0.0.1:58138 fd=42 name= age=3 idle=3 flags=N db=0 sub=2 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=446 addr=127.0.0.1:58139 fd=43 name= age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=lrange
```

**Comment by redroot** [comment] 2016-02-17 16:32
Ah, ive just noticed this line: https://github.com/OptimalBits/bull/blob/master/lib/queue.js#L65 ... if I pass a createClient function as part of the options I can cache the client there right?

**Comment by redroot** [comment] 2016-02-17 17:44
So I've modified the createQueue method like so

```

var redisClient = null;

var createQueue = function(name) {
  return bull(name, 6379, '127.0.0.1', {
    createClient: function() {
      if (!!redisClient) {
        return redisClient;
      } else {
        redisClient = redis.createClient(6379, '127.0.0.1');
        return redisClient;
      }
    }
  });
};
```

and got: 

```
Starting url-download worker 1 of 5
Starting url-download worker 2 of 5
Starting url-download worker 3 of 5
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at RedisClient.addListener (events.js:179:15)
    at /Users/lukewilliams/work/refme/refme-file-service/node_modules/bull/lib/queue.js:108:12
    at Array.forEach (native)
    at new Queue (/Users/lukewilliams/work/refme/refme-file-service/node_modules/bull/lib/queue.js:107:45)
    at Queue (/Users/lukewilliams/work/refme/refme-file-service/node_modules/bull/lib/queue.js:47:12)
    at createQueue (/Users/lukewilliams/work/refme/refme-file-service/test.js:8:10)
    at /Users/lukewilliams/work/refme/refme-file-service/test.js:45:17
    at Function._.times (/Users/lukewilliams/work/refme/refme-file-service/node_modules/underscore/underscore.js:1317:44)
    at /Users/lukewilliams/work/refme/refme-file-service/test.js:43:5
    at Function._.each._.forEach (/Users/lukewilliams/work/refme/refme-file-service/node_modules/underscore/underscore.js:153:9)
    at Object.<anonymous> (/Users/lukewilliams/work/refme/refme-file-service/test.js:42:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
Starting url-download worker 4 of 5
Starting url-download worker 5 of 5
Starting file-creation worker 1 of 3
Starting file-creation worker 2 of 3
Starting file-creation worker 3 of 3
Starting pdf-process worker 1 of 5
Starting pdf-process worker 2 of 5
Starting pdf-process worker 3 of 5
(node) warning: possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at RedisClient.addListener (events.js:179:15)
    at new Queue (/Users/lukewilliams/work/refme/refme-file-service/node_modules/bull/lib/queue.js:127:16)
    at Queue (/Users/lukewilliams/work/refme/refme-file-service/node_modules/bull/lib/queue.js:47:12)
    at createQueue (/Users/lukewilliams/work/refme/refme-file-service/test.js:8:10)
    at /Users/lukewilliams/work/refme/refme-file-service/test.js:45:17
    at Function._.times (/Users/lukewilliams/work/refme/refme-file-service/node_modules/underscore/underscore.js:1317:44)
    at /Users/lukewilliams/work/refme/refme-file-service/test.js:43:5
    at Function._.each._.forEach (/Users/lukewilliams/work/refme/refme-file-service/node_modules/underscore/underscore.js:153:9)
    at Object.<anonymous> (/Users/lukewilliams/work/refme/refme-file-service/test.js:42:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at RedisClient.addListener (events.js:179:15)
    at Queue.process (/Users/lukewilliams/work/refme/refme-file-service/node_modules/bull/lib/queue.js:186:16)
    at /Users/lukewilliams/work/refme/refme-file-service/test.js:46:11
    at Function._.times (/Users/lukewilliams/work/refme/refme-file-service/node_modules/underscore/underscore.js:1317:44)
    at /Users/lukewilliams/work/refme/refme-file-service/test.js:43:5
    at Function._.each._.forEach (/Users/lukewilliams/work/refme/refme-file-service/node_modules/underscore/underscore.js:153:9)
    at Object.<anonymous> (/Users/lukewilliams/work/refme/refme-file-service/test.js:42:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Starting pdf-process worker 4 of 5
Starting pdf-process worker 5 of 5
```

Fixed the issue will loads of redis client connections being created...however caused the wierd error above.

I'm a little out of touch with this, is there a max limit in Node for EventEmitter listeners?

**Comment by manast** [comment] 2016-02-23 21:59
This is a duplicate of #161 I have added it to 1.0 milestone, since reducing the number of redis connections is a low hanging fruit and has some significant economic impact, as you mentioned on services as heroku.

**Comment by doublerebel** [comment] 2016-10-23 18:58
It's possible to share a connection for all the queue.client and queue.bclient, and another connection for all queue.eclient (subscriber connection).  Subscriber connections can only subscribe, trying to share those connections with a non-subscribing connection results in the error:
```
ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```
Relevant:
http://stackoverflow.com/questions/22668244/should-i-use-separate-connections-for-pub-and-sub-with-redis

To share the clients, after creating a queue instance just set the .client, .bclient, and .eclient properties of the queue to the respective redis client instances you have created.

**Comment by gblock0** [comment] 2017-01-17 21:16
@manast is this in 2.0+?

**Comment by ianstormtaylor** [comment] 2017-03-16 00:07
Just ran into this same issue on Heroku. Is this already in the current version? If not, any idea when it will land? I can't tell if it already did or not because the past issues about it are all closed?

Or is there a workaround? I feel like this means I need use Kue instead... which is sad.

**Comment by manast** [comment] 2017-03-16 10:34
@ianstormtaylor I can work on a fix but I need to know what is the requirement. Is it to be able to reuse the same redis connection for different queues, meaning that you have several workers in the same nodejs process reusing connection, or is it to reduce the number of connections used for every worker?
Reusing clients should not be very difficult to fix, on the other hand reducing connections it would be possible to go maximum from 3 to 2 connections in a pure worker (i.e., a worker that never calls to methods such as adding jobs, checking job counts, cleaning the queue etc, since all those operations requires an extra connection).

**Comment by ianstormtaylor** [comment] 2017-03-16 18:50
Hey @manast, thanks for the reply!

From what I understand, reusing the same Redis connection for different queues would solve the problem. It sounds like that would mean that all queues created in a node process only ever take up 3 connections—2 would be even better!

Right now Heroku (and presumably other PaaS) limits the amount of connections that Redis can open based on your plan type:

```
Free    - 20 connections
$15/mo  - 40 connections
$30/mo  - 80 connections
$60/mo  - 200 connections
$120/mo - 400 connections
...
```

In my case, I've got three services or "apps" in Heroku terms (`api`, `dashboard`, and `workers`). Right now the `api` and `dashboard` each open a single queue, piping events to the `workers` service. 

But since the Bull docs said that "queues are cheap", I architected the system to create a queue for each type of job type I'm using. So `workers` has many queues, two to listen from `api` and `dashboard`, and then one for every type of async task that it performs.

It's not great that the number of different types of tasks I create is limited by the Heroku Redis plan I'm on. Currently, I've got:

```
api       - 3 connections
dashboard - 3 connections
workers   - 3 + 3 + 3n connections
```

And for me, right now `n` is 3, so I'm looking at 21 connections, which means my staging environment can't use the Heroku free plan. Which is the worst... But it's not crazy to think that the number of queue types I have might scale to 10+, in which case I'm looking at 300+ connections, which requires being on the $120/mo Heroku plan, even for staging! And that's not even factoring in having to scale the `api` or `dashboard` services up to multiple processes. It starts multiplying really fast.

Does that make sense?

I'd really appreciate being able to stick with Bull and get around this problem somehow! I really like everything else about how the API is designed.

**Comment by ianstormtaylor** [comment] 2017-03-16 19:44
@manast also I just realized that the problem cascades, because of the way [Toureiro](https://github.com/Epharmix/Toureiro/blob/master/lib/models/job.js#L14) is architected, whenever you view a job in the interface is opens up more connections, so there's yet another multiplier! Right now trying to visit the Toureiro interface crashes my Heroku Redis instance.

**Comment by manast** [comment] 2017-03-16 19:51
@ianstormtaylor ok I see where you are going. Currently, and I mean theoretically, you could reuse 2 of the three connections. 1 connection is being used in block mode, which means it cannot be reused. This means that you will always need at least 1 connection per worker and then 2 connections that can be reused by the other workers assuming that they are in the same nodejs process. I will work a bit on this now, see if I can find a quick and acceptable solution.
We also support queues without the blocking connection, that means they poll the redis server to check if new jobs have arrived, in this case the same connection could be used for all the workers but you will get increased latency and a bit of extra work for the redis instance when polling (probably not very severe, of course depends on your applications requirements)

**Comment by ianstormtaylor** [comment] 2017-03-16 20:24
@manast just to make sure I understand. As I see it right now the system requires:

- `3 connections` per queue.

And it sounds like with the changes, the lowest it can get to is:

- `2 connections` per process.
- `1 connection` per queue.

Is that true?

Such that my situation would go from being `3 + 3 + 3 + 3 + 3*n = 21`, to `3 + 3 + 2 + n = 13`?

**Comment by manast** [comment] 2017-03-16 20:35
I think you got the math right :). You can now update to vesion 2.2.4 and try the connection reuse to see if theory matches practice.
Example: 
```js
var client, subscriber;
  client = new redis();
  subscriber = new redis();

  var opts = {
    redis: {
      opts: {
        createClient: function(type){
          switch(type){
            case 'client':
              return client;
            case 'subscriber':
              return subscriber;
            default:
              return new redis();
          }
        }
      }
    }
  }
  var queueFoo = new Queue('foobar', opts);
  var queueQux = new Queue('quxbaz', opts);
```

**Comment by ianstormtaylor** [comment] 2017-03-16 21:15
Thanks @manast for the quick fix! That definitely helped! Locally, it reduced my usage from `26` to `18` connections. (Slightly different environment from staging/production, but good!)

Is that the theoretical minimum? Or did you say that it's possible to reduce the `2 connections` required per process to one?

Also, I was researching Kue and came across this thread: https://github.com/Automattic/kue/issues/366, which sounds like they have a similar amount of connections being created—if not slightly more now.

Also, for others, here's how I setup a `./utils/create-queue.js`:

```js

import Redis from 'ioredis'
import Queue from 'bull'

/**
 * Environment variables.
 *
 * @type {Mixed}
 */

const { REDIS_URL } = process.env

/**
 * Shared clients.
 *
 * @type {Redis}
 */

const client = new Redis(REDIS_URL)
const subscriber = new Redis(REDIS_URL)

/**
 * Create a new queue with `name`.
 *
 * @param {String} name
 * @return {Queue}
 */

function createQueue(name) {
  return new Queue(name, {
    redis: {
      opts: {
        createClient(type) {
          switch (type) {
            case 'client': return client
            case 'subscriber': return subscriber
            default: return new Redis(REDIS_URL)
          }
        }
      }
    }
  })
}

/**
 * Export.
 *
 * @type {Function}
 */

export default createQueue

```

**Comment by ianstormtaylor** [comment] 2017-03-16 21:17
Although sadly I think Toureiro is still going to be unusable, since it's architected in a pretty bad way that means every time you change queues in the interface you're opening more connections, and currently it does no pooling.

**Comment by manast** [comment] 2017-03-16 21:28
Maybe https://github.com/ShaneK/Matador works better for you.

Regarding reducing even more the number of connections. I have a fix planed that will reduce one connection when you use a pure worker (i.e. a worker only using the process method). So that will mean 1 connection per process and 1 per queue.

**Comment by manast** [comment] 2017-03-17 18:55
I will close this issue since I considered it fixed, reopen if needed.

**Closed by manast** 2017-03-17 18:55 UTC
Labels: enhancement

**Comment by cosydney** [comment] 2022-04-21 15:55
hey @ianstormtaylor, 

First, thank you for showing your answer to that topic. I'm having a similar problem and found your answer while searching why I had so many clients. 

Your provided answer works great locally on my computer but not in production on Heroku. It seems no keys are being created even though I can see there are a few connections to redis.. 

Any idea where that could come from? 

Thank you !

**Comment by cosydney** [comment] 2022-04-21 16:39
I followed the patterns in the bull doc and found this alternative which works for me in production: 

```javascript
const { REDIS_URL } = process.env;

const Redis = require('ioredis');
let client;
let subscriber;

const opts = {
  // redisOpts here will contain at least a property of connectionName which will identify the queue based on its name
  createClient: function (type, redisOpts) {
    switch (type) {
      case 'client':
        if (!client) {
          client = new Redis(REDIS_URL, redisOpts);
        }
        return client;
      case 'subscriber':
        if (!subscriber) {
          subscriber = new Redis(REDIS_URL, redisOpts);
        }
        return subscriber;
      case 'bclient':
        return new Redis(REDIS_URL, redisOpts);
      default:
        throw new Error('Unexpected connection type: ', type);
    }
  }
}

const queueFoo = new Queue('foobar', opts);
const queueQux = new Queue('quxbaz', opts);
```

**Comment by raghavbitqit** [comment] 2024-04-23 05:50
`import * as Bull from "bull";
import * as config from "config";
import { injectable} from "inversify";
import Redis from "ioredis";

@injectable()
export class BullQueueService {
    private static bullQueues = new Map<string, Bull.Queue>();
    private static client : Redis;
    private static subscriber : Redis;
    constructor() {
    }

    opts = {
        createClient: (type: 'client' | 'subscriber' | 'bclient',redisOpts) => {
            switch (type) {
                case 'client':
                    if(!BullQueueService.client){
                        BullQueueService.client = new Redis(config.get("redis.cache"),redisOpts);
                    }
                    return BullQueueService.client;
                case 'subscriber':
                    if(!BullQueueService.subscriber){
                        BullQueueService.subscriber = new Redis(config.get("redis.cache"),{
                            maxRetriesPerRequest:null,
                            enableReadyCheck:false
                        });
                    }
                    return BullQueueService.subscriber;
                case 'bclient':
                    return new Redis(config.get("redis.cache"),{
                        maxRetriesPerRequest:null,
                        enableReadyCheck:false
                    });
                default:
                    throw new Error('Unexpected connection type: ' + type);
            }
        }
    }

    public getBullQueue(queueName: string): Bull.Queue {
        console.log(config.get("redis.cache"))
        if (!BullQueueService.bullQueues.has(queueName)) {
            console.log(`Creating new queue instance for: ${queueName}`);
            const queue = new Bull(queueName, this.opts);
            BullQueueService.bullQueues.set(queueName, queue);
        } else {
            console.log(`Reusing existing queue instance for: ${queueName}`);
        }
        return BullQueueService.bullQueues.get(queueName);
    }
}
` 
Ok as explained above , I have writtten this code and there are multiple  class where  I instantiate this class to get the queue instance to process job and to add the job. With this logic is it work fine or not because earlier I am getting client limit reached on azure . So I want to know whether my code is correct  or not

**Comment by raghavbitqit** [comment] 2024-04-23 05:52
And Can you please explain that if  have a single queue and a process method of concurrency = 10 then how much client connection it will create with this logic and from earlier one ??
