### ISSUE TITLE
Queue clean removes other non-bull key entries as well

### ISSUE THREAD

**Issue by jeetkr** [OptimalBits/bull#819] opened 2017-12-22 09:49 UTC
I am using my redis for bull as well as for other processes as well. All bull keys start with bull:* and any Queue.clean() should only delete entries with are created by bull. After I executed defaultQueue.clean(1,'completed') , I promptly see the completed queue cleared, but I see my other key entires cleared as well, keys like "1234","1235",etc . This issue did not happen in the earlier version which I was using, which was 3.0.0-rc.9. The current version I am using is 3.3.7, and I see this issue.
Is this a known issue and has a workaround for now?

**Comment by manast** [comment] 2017-12-22 20:39
Could you please create a test case that reproduces the issue?

**Comment by jeetkr** [comment] 2017-12-26 12:58
Dont have a test case for this. Just create few redis lists with keys name different than those of bull, for example key names like "123","234",etc with some values in those redis lists just to debug. To insert some values in those list, just do a lpush for those keys. Now do a Queue.clean(). You will see those lists deleted ,that is, you wont be able to find those keys.
Please let me know if this is confusing or not clear
Thanks,
Jeet

**Comment by manast** [comment] 2017-12-27 11:19
There are many reasons why a reproducible test case must be provided, I will update the rules for creating issues to avoid misunderstandings in the future.
Nevertheless, I created a test case myself based on your instructions:
```
const Queue = require('../lib/queue.js');
const testQueue = new Queue('test');

const Redis = require('ioredis');


const redis = new Redis();

redis.lpush('123', [1, 2, 3]);

redis.lrange('123', 0, -1).then(function(list){
  console.log(list);

  testQueue.clean(100).then(function(){
    redis.lrange('123', 0 , -1).then(function(list){
      console.log(list);
    });
  })
});
```
It outputs: 
```
[ '3', '2', '1' ]
[ '3', '2', '1' ]
```

So it seems to be correct. Please provide a working test code that reproduces the issue or close it.

**Closed** 2018-01-06 11:44 UTC
Labels: cannot reproduce
