### ISSUE TITLE
Cron not working as expected with multiple cron jobs

### ISSUE THREAD

**Issue by jeetkr** [OptimalBits/bull#675] opened 2017-08-25 12:35 UTC
I am adding the following two cron jobs:
```
//to run every minute
Queue.addCron({task: Queue.CRON.AUTO_LIKE_ONBOARDING_JAM, data: {}},{repeat: {cron: '*/1 * * * *'}});
//to run every 5 minutes
Queue.addCron({task: Queue.CRON.DELETE_OLD_INCOMPLETE_JAMS, data: {}},{repeat: {cron: '*/5 * * * *'}});

//addCron just adds it to the main queue:
jobQueue.addCron = function (data,repeat){
    defaultQueue.add(data,repeat);
}
```
This does not work as expected; I see first process end and not repeat, while the second process runs just fine.
Does the second cron somehow overwrite the first one?

**Comment by ritter** [comment] 2017-08-25 14:20
Take a look at: https://github.com/harrisiirak/cron-parser mentioned in the docs.
I believe you want: "* */1 * * * *" and "* */5 * * * *" respectively. As you have it, it appears it would try and run every second and every 5 seconds.

**Comment by jeetkr** [comment] 2017-08-25 14:47
I had tried this and various other configurations of cron formats in the above link, no avail. Only the second cron keeps running, while the first one shuts down after some time.

**Comment by manast** [comment] 2017-08-25 14:51
@jeetkr which version of bull are you using?

**Comment by ritter** [comment] 2017-08-25 14:52
looks these are using the same Queue, so you probably need to specify a named process for them.
try calling `defaultQueue.add( taskName, data, repeat);`

**Comment by jeetkr** [comment] 2017-08-25 15:00
@manast from my package.json: "bull": "^3.0.0-rc.4"
@ritter will try that

**Comment by ritter** [comment] 2017-08-25 15:05
For what its worth, install 3.0.0-rc.9 there were big changes that came about in rc.5 and many bugs fixed since then.

**Comment by jeetkr** [comment] 2017-08-25 16:33
@ritter no avail with separate queue as well as with 3.0.0-rc.9

**Comment by manast** [comment] 2017-08-25 17:18
@jeetkr can you write a minimal test so that I can reproduce the issue?

**Comment by jeetkr** [comment] 2017-08-26 14:19
@manast didnt write a test case, but here is what I did:
adding jobs:
```
Queue.addCron('deleteOldIncompleteJams',{task: Queue.CRON.AUTO_LIKE_ONBOARDING_JAM, data: {}},{repeat: {cron: '* */1 * * * *'}});
Queue.addCron('autoLikeOnboardingJam',{task: Queue.CRON.DELETE_OLD_INCOMPLETE_JAMS, data: {}},{repeat: {cron: '* */5 * * * *'}});
```
and procesing job:
```
jobQueue.processCron1 = function () {
    defaultQueue.process('deleteOldIncompleteJams',function (job, done) {
        console.log("done");
    })
}

jobQueue.processCron2 = function () {
    defaultQueue.process('autoLikeOnboardingJam',function (job, done) {
        console.log("done");
    })
}
```
The issue which happens is instead of these job running at an interval of 1 minutes and 5 minutes,respectively according to the cron expression, both these jobs run at an interval of 1 seconds. Probably there is something wrong with this type of cron parsing.
I say this because if I change the crons to '1 * * * * *' and '* 1 * * * *' respectively, I see jobs running at 1 minutes and 1 hour as expected. So, I suspect the issue with parsing the cron repeat times when they are in */X format.

**Comment by ritter** [comment] 2017-08-26 18:40
You should be calling `done()` in your process handler.

**Comment by jeetkr** [comment] 2017-08-27 13:48
@ritter I do have a done() call in the end. Had removed when I was pasting code here just to avoid clutter, updated now

**Comment by manast** [comment] 2017-08-27 20:46
@jeetkr I just wanted to update that I have experiencing strange results running your code. I am debugging it right now.

**Comment by manast** [comment] 2017-08-27 22:10
I am starting to suspect that the error comes from cron-parser, the module we use in bull to generate the next repeat date. I will investigate more tomorrow.

**Comment by manast** [comment] 2017-08-27 22:16
I found that if you write the expression with only 5 asterisks:
"*/1 * * * *" and "*/5 * * * *" it runs the jobs every minute respective every 5 minutes. Remember to clean redis before you try this.

**Comment by jeetkr** [comment] 2017-08-28 04:48
This works nicely. Thanks @manast . Feel free to close this issue, or else if you want to wait for the cron-parser fix.

**Comment by ritter** [comment] 2017-08-28 13:55
I just realized I wrote my 5 minute repeat cron as follows: `{ "cron": "0 */5 * * * *" }` and it's been working well for me.

**Comment by manast** [comment] 2017-08-30 07:32
I will close this because the problem is in the expression itself: http://cronexpressiondescriptor.azurewebsites.net/?expression=*+*%2F5+*+*+*+*&locale=en

**Closed by manast** 2017-08-30 07:32 UTC
