### ISSUE TITLE
Queue Stuck in Active

### ISSUE THREAD

**Issue by msyahidin** [OptimalBits/bull#2160] opened 2021-09-15 07:32 UTC
## Description
I am using nestjs as my base project, using just example in Nestjs Queue Example https://github.com/nestjs/nest/tree/master/sample/26-queues. 
Sometimes queue successfully added but did not processed, it just logging 
`Processing job at interval 0` until 100 and completed, i added 21 queues, but only the 5th queue like this.

<img width="1440" alt="Screen Shot 2021-09-15 at 13 58 46" src="https://user-images.githubusercontent.com/24245457/133385739-aa3c0a6e-0f79-4198-9105-a811ea84ee53.png">

## Minimal, Working Test code to reproduce the issue.
I have using queue when user add batch insert, but just using this example this issue happen.

Adding queue by get API request
```
@Controller('audio')
export class AudioController {
  constructor(@InjectQueue('audio') private readonly audioQueue: Queue) {}

  @Post('transcode')
  async transcode() {
    await this.audioQueue.add('transcode', {
      file: 'audio.mp3',
    });
  }
}
```

Handling queue, this class or function is not executed in 5th queue
```
@Processor('audio')
export class AudioProcessor {
  private readonly logger = new Logger(AudioProcessor.name);

  @Process('transcode')
  handleTranscode(job: Job) {
    this.logger.debug('Start transcoding...');
    this.logger.debug(job.data);
    this.logger.debug('Transcoding completed');
  }
}
```

## Bull version
3.29.2

## Additional information
Deps
```
"dependencies": {
    "@nestjs/bull": "^0.4.1",
    "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/platform-express": "^7.6.15",
    "bull": "^3.29.2",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6"
  },
```
I have submitted an issue on nestjs/bull repo as well: https://github.com/nestjs/bull/issues/924
source code: https://github.com/nestjs/nest/tree/master/sample/26-queues

**Comment by manast** [comment] 2021-09-15 07:52
Since the issue is opened in nestjs/bull I will close this one since we do not have bull specific code either that reproduces the issue.

**Closed** 2021-09-15 07:57 UTC
