### ISSUE TITLE
Error processing job: SyntaxError: Unexpected token u in JSON at position 

### ISSUE THREAD

**Issue by jahraphael** [OptimalBits/bull#482] opened 2017-04-01 00:18 UTC
Hi there,

I am using Bull 2.6.5 (Redis 3.2.4) and Node 6.9.4 across about 30 containers each running a single queue consumer process with concurrency = 2.

**Problem I'm Running Into**
Over time my queues start to fill up with invalid jobs that Bull does not remove, and I start to see many `Error processing job: SyntaxError: Unexpected token u in JSON at position` errors in the logs:

```
Error processing job: SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Function.Job.fromData (node_modules/bull/lib/job.js:503:33)
    at node_modules/bull/lib/job.js:65:18
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

When these errors occur the process is not killed. Instead these jobs just repeatedly get re-attempted and never removed. I think because the error is happening at the point where the Job object would actually be created, so it is not able to handle this like a standard job failure.

When I just checked I had about ~6000 jobs in this state.

**What I've Done to Debug**
In node:
- When I print out the contents of `jobData` inside of `Job.fromId` I see that in these failure cases it is always either `{}` or `{ delay: '0' }`.

In redis-cli:
```
> hgetall bull:rio-bnet-queue-111-us:1986600
1) "delay"
2) "0"
```

**How to reproduce**
I do not have a solid code-based reproduction process. I'm not sure *why* I end up with jobs with the empty data as I mentioned above. I'm not doing any manual redis queue manipulation in my actual code, but I believe you would be able to reproduce the problem by setting one of your jobs in your queue to be a hash map with just a single entry. Something like:

`hmset bull:rio-bnet-queue-111-us:1986600 delay 0`

**Workaround**
My current workaround here, which I just got setup, is to proactively check for this invalid job state in `Job.fromId`, craft a `Job` with the same Id (and no data), and then return a rejected promise to remove this job from the queue (since it is invalid).

```
Job.fromId = function(queue, jobId){
  // jobId can be undefined if moveJob returns undefined
  if(!jobId) {
    return Promise.resolve();
  }
  return queue.client.hgetall(queue.toKey(jobId)).then(function(jobData){
    if(jobData.data === undefined || jobData.opts === undefined) {
      var job = new Job(queue, {}, {});
      job.jobId = jobId;
      return Promise.reject(job.remove());
    }
    return Job.fromData(queue, jobId, jobData);
  });
};
```

This appears to properly clean up these bugged jobs when they're encountered, but I understand it may not be an appropriate solution for the library. I'd be happy to help contribute something more appropriate, but I'd be curious to get @manast opinions on this whole situation.

Is there additional useful information could I provide to help narrow this down?

**Comment by manast** [comment] 2017-04-01 09:13
Thanks for the report. The first thing I will do is be sure than when this happens the job is failed, so that we do not keep corrupt jobs in the queue. The second part, probably much more difficult is to fix the cause creating this corrupted jobs in the first place.

**Comment by 0fork** [comment] 2017-05-19 05:18
I just encountered a variation of this same problem with 2.2.6 and it seems that there's no way to catch this. `error` event for the queue doesn't trigger and `process()` doesn't seem to support `.catch()`. `process()` will just keep processing the problem job over and over again.

I was able to get this done by trying `fooqueue.add({ data: 'bar' }, (err, job_id) => {})`. For some reason the callback causes `unexpected end of JSON input`.

**Comment by bradvogel** [comment] 2017-05-19 05:29
`unexpected end of JSON input` was caused by a job corruption issue in Bull 2.x. It should now be fixed in Bull 3.x. Can you test using that version?

**Comment by 0fork** [comment] 2017-05-19 05:35
@bradvogel unfortunately I already changed everything back already and compiled docker images but hopefully I will have some time to test this later. Last time I tried 3 it broke everything so I went back to 2 ;)

**Comment by bradvogel** [comment] 2017-05-19 05:38
Please try again and let us know what breaks. We're very close to releasing as the new stable version. So we'd really like to figure out what broke.

**Comment by bradvogel** [comment] 2017-05-21 07:36
Note that https://github.com/OptimalBits/bull/issues/498 is the last job corruption issue in Bull 3.0.0. When that is fixed, it should be ready to test.

**Comment by manast** [comment] 2017-05-24 12:45
This problem should be now resolved in latest bull (3.0.0), re-open if you can still reproduce it.

**Closed by manast** 2017-05-24 12:45 UTC

**Comment by pavelmazurov1** [comment] 2017-08-14 12:59
Hi! Getting this error in bull 3.0.0-rc.4

**Comment by manast** [comment] 2017-08-14 14:36
there are some improvements regarding that part of the codebase in rc5, so maybe it is fixed now.
