### ISSUE TITLE
jobId does not work on cron repeat job

### ISSUE THREAD

**Issue by betimer** [OptimalBits/bull#1701] opened 2020-04-15 05:57 UTC
## Description

Create cron job to run the task periodically. But everytime the service gets redeployed new cron job will be added. Here is the data in the redis.

I suspect the `jobId` does not work as shown in the log that it is duplicate

code I use:
```javascript
sitemapQueue.add(
      'sitemap',
      { handle: 'tester-dev' },
      { jobId: 'sitemap-tester-dev', repeat: { cron: '*/3 * * * *' } }
    )
```

```
127.0.0.1:6379> hgetall "bull:sitemap-queue:repeat:a28b04b6cffac6e013a7ea8773468da7:1586925000000"
 1) "timestamp"
 2) "1586924898378"
 3) "delay"
 4) "0"
 5) "priority"
 6) "0"
 7) "data"
 8) "{\"handle\":\"tester-dev\"}"
 9) "returnvalue"
10) "null"
11) "processedOn"
12) "1586925000001"
13) "finishedOn"
14) "1586925002020"
15) "opts"
16) "{\"repeat\":{\"count\":1,\"cron\":\"*/3 * * * *\",\"jobId\":\"sitemap-tester-dev\"},\"jobId\":\"repeat:a28b04b6cffac6e013a7ea8773468da7:1586925000000\",\"delay\":101622,\"timestamp\":1586924898378,\"prevMillis\":1586925000000,\"attempts\":1}"
17) "name"
18) "sitemap"
```

## Minimal, Working Test code to reproduce the issue.

Stop the node process and start the it again.

## Bull version

3.13.0

**Comment by manast** [comment] 2020-04-15 07:21
Can you please provide a test case that reproduces your issue?

**Comment by betimer** [comment] 2020-04-15 22:31
@manast I stop the node process and start the it again.

**Comment by betimer** [comment] 2020-04-16 01:24
@manast I updated the description, to make it easy copy paste and debug

**Comment by betimer** [comment] 2020-04-17 02:04
This may be because of https://github.com/OptimalBits/bull/blob/9ba3e409c5942f7df40d05255befaeb93c071755/lib/repeatable.js#L184

I think we should determine the job based only on jobId (instead of jobId+cron), how do you think? @manast

**Comment by ralexandr** [comment] 2020-05-01 15:38
Met same issue

**Comment by gaganshera** [comment] 2020-05-28 12:15
Ran into same issue. @manast any update about a fix for this? This is preventing usage of bull as a cron-job manager in multi-clustered environments.

**Comment by cerino-ligutom** [comment] 2020-10-19 10:35
Experiencing the same issue.

**Comment by manast** [comment] 2020-10-20 07:44
Not sure what the issue is here. If I test with this code:
```
const Queue = require('../index');

const queue = new Queue('repeater-2');

queue.process(async function(job) {
  console.log('processing at', new Date(), job.id);
});

queue.add(
  { job: 'data' },
  { jobId: 'sitemap-tester-dev', repeat: { cron: '*/3 * * * * *' } }
);
```

I can call this script as many times I want and the cron job will always be executed every 3 seconds, as expected...

**Comment by ZECTBynmo** [comment] 2021-02-06 17:06
@manast My suggestion would be to start up a second instance of the script with the same code. The expected behavior is:
- The job fails to be added to the queue, because the jobId is being used twice (this does not happen)
- The repeating job only executes once across the cluster, because there should be only one repeating job (the job will run twice, one on each)

**Comment by ezain501** [comment] 2021-07-11 10:37
@manast 


> Not sure what the issue is here. If I test with this code:
> 
> ```
> const Queue = require('../index');
> 
> const queue = new Queue('repeater-2');
> 
> queue.process(async function(job) {
>   console.log('processing at', new Date(), job.id);
> });
> 
> queue.add(
>   { job: 'data' },
>   { jobId: 'sitemap-tester-dev', repeat: { cron: '*/3 * * * * *' } }
> );
> ```
> 
> I can call this script as many times I want and the cron job will always be executed every 3 seconds, as expected...

Running the script second time, should not create the cron job again.

**Closed** 2021-10-31 20:24 UTC
Labels: wontfix, cannot reproduce
