### ISSUE TITLE
Clarify lock functionality

### ISSUE THREAD

**Issue by Gourmentt** [OptimalBits/bull#660] opened 2017-08-16 12:14 UTC
Hello, could you explain, when bull are locking job?
I see only one call and it's "extendLock" before calling job handler.

Another one question:
If job is in "active" state and we are rebooting server, job is locked. We starting server and then after some time lock disappear. But I don't see any calls to "releaseLock" method. 
Thanks in advance

**Comment by manast** [comment] 2017-08-16 12:57
Locks expire automatically since they use redis expire command, thats why it disapears. Locks are extended during a job lifetime so that no other worker picks the same job believing it has been stalled.

**Comment by Gourmentt** [comment] 2017-08-16 14:45
Okay, got it, but when locks are creating? I see only one place - it's `lockExtender` function

**Comment by Gourmentt** [comment] 2017-08-16 14:47
Okay, I see - in `moveToActive-4.lua` it is created, and lock renew during processing job

**Comment by manast** [comment] 2017-08-17 11:09
I will close this issue since it seems as it is clear now :)

**Closed by manast** 2017-08-17 11:09 UTC

**Comment by cristianfd** [comment] 2017-12-22 22:50
@Gourmentt @manast Sorry for reopen this issue again but I've had the `job stalled more than allowable limit` error. It seemed strange to me that it did not appear before because I'm transcoding video.
The solution isn't increase the `lockDuration` value because I like it with low values (in my case 5 minutes), but sometimes we transcode video that takes more than 5 minutes. We come from Kue and there we have a "lock renewer" that we call it when each bash stdout call was fired. Here I'm not sure if it can be done and who; I've found [extendLock](https://github.com/OptimalBits/bull/blob/b28ed43138aded937ff2529e658e2a5fa324d730/lib/scripts.js#L225) but I'm not sure if calling that process is the correct form.

**Comment by manast** [comment] 2017-12-22 23:25
the lock is renewed automatically as long as you do not keep node's event loop busy. If the transcoding is a synchronous operation, then I recommend you that you use a external worker instead: https://github.com/OptimalBits/bull#separate-processes

**Comment by cristianfd** [comment] 2017-12-23 13:20
Yes, the transcoder is synchronous. I will test it with separate process, thanks.

**Comment by cristianfd** [comment] 2017-12-28 13:08
I've read more and it seems to be redis connection error but I said previous, I have other progress system that works without problems. What happens if it's a micro-cut? Bull or perhaps bluebird consider this type of connections?

**Comment by manast** [comment] 2017-12-28 13:31
This latest "timeout" error is not the same as the initial issue. I wondering, do you have a more complete stacktrace than that? could you enable bluebird long stack traces and test again? (http://bluebirdjs.com/docs/api/promise.longstacktraces.html)

**Comment by cristianfd** [comment] 2017-12-28 13:35
Oh, I thank you a lot for that clue. I'll take a look and I'll tell you when I know something. 
On the other hand I've not tried to change the redis config values...

**Comment by manast** [comment] 2017-12-28 17:23
I do not think it is ioredis related actually, it is supposed to keep the connection alive for ever and reconnect on error. Also, it seems as if it was some command that was issued but that timedout. Ae you using the default ioredis options?

**Comment by cristianfd** [comment] 2017-12-29 13:27
After long tests, it's failing with 'operation timed out' and the weird thing is that the transcoding process is still working (I know that I must implement a kill command but this isn't the question) because I can see on top command. So it isn't a process error, it doesn't finished when the error is triggered. I'm still doing tests.
This is the stack trace:
```
TimeoutError: operation timed out
                  at ontimeout (timers.js:478:11)
                  at tryOnTimeout (timers.js:302:5)
                  at Timer.listOnTimeout (timers.js:262:5)
              From previous event:
                  at Queue.processJob (/app/node_modules/bull/lib/queue.js:902:31)
              From previous event:
                  at /app/node_modules/bull/lib/queue.js:816:12
                  at runCallback (timers.js:800:20)
                  at tryOnImmediate (timers.js:762:5)
                  at processImmediate [as _immediateCallback] (timers.js:733:5)
              From previous event:
                  at /app/node_modules/bull/lib/queue.js:814:43
                  at _combinedTickCallback (internal/process/next_tick.js:131:7)
                  at process._tickCallback (internal/process/next_tick.js:180:9)
```
In which moment is operation time out triggered? I will search following the stack trace.

About redis: I've it with default options but I'm not really convinced that the problem is redis.

**Comment by cristianfd** [comment] 2017-12-29 13:39
I've the timeout option set to 1200000 (20 minutes). The REFERENCE.md says: _The number of milliseconds after which the job should be fail with a timeout error [optional]_ and I now think, what happens if I delete the timeout (null or nothing) and the transcoding process never ends?
I'll test it.

**Comment by manast** [comment] 2017-12-29 14:14
yes, your process is timing out, this works as designed. Either increase to something acceptable or do not specify any and then it will never timeout. Regarding killing the process that has timed out w have an issue for this: https://github.com/OptimalBits/bull/issues/718

**Comment by cristianfd** [comment] 2017-12-29 14:20
Oh, the test just ended and it WORKS. Was timeout issue, thanks for your time.
Now I will checkout #718 and see how to kill process if really it has ended but the process is still blocked (internal or not handled external error).
