### ISSUE TITLE
node_redis deprecation messages

### ISSUE THREAD

**Issue by kenjones-cisco** [OptimalBits/bull#272] opened 2016-03-16 16:38 UTC
```
node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```
```
node_redis: Deprecated: The EVAL command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```

After upgrading to Bull 0.7.2,
```
├─┬ bull@0.7.2
│ ├── node-uuid@1.4.7
│ ├── redis@2.5.1
│ └── semver@4.3.6
```
The dependent redis library was upgraded to 2.5.1, resulting in all of the above messages.
Associated node-redis changelog (https://github.com/NodeRedis/node_redis/blob/master/changelog.md#v250-1---07-mar-2015)

**Comment by manast** [comment] 2016-03-16 16:58
actually quite good stuff to help us find bugs in our code, I will upgrade and run the unit tests to solve those issues.

**Comment by kzima** [comment] 2016-03-16 22:01
I can also confirm that deprecation messages appear on redis 3.0.7 and 2.8.11 if that helps.

**Comment by manast** [comment] 2016-03-16 22:03
It is not dependent on redis version but on the node-redis version...

**Comment by BridgeAR** [comment] 2016-03-17 11:03
Those warnings indeed indicate real errors in your code, as it's unlikely that anyone would want to safe "undefined" values in redis.

What is happening is something like this:
```js
function safe() {
    // do stuff
    client.hmset.apply(client, arguments);
}
safe('test', 'foo', 'bar', undefined, undefined, function callback (err, res) { /* do stuff */ });
```
So the hmset is called with the right number of arguments so redis does not deny that and it'll safe two fields. One is called 'foo' with the value 'bar' and one is called 'undefined' with the value 'undefined'. This is just a theoretical example and any of the arguments could be undefined and maybe it's just either a field name, the value or the key that is undefined.

**Comment by nibblesnbits** [comment] 2016-03-18 23:49
I think this could be considered a duplicate of #271.

**Comment by lipp** [comment] 2016-03-24 10:21
:+1:  getting also 

```
node_redis: Deprecated: The HMSET command contains a "undefined" argument
```

**Comment by manast** [comment] 2016-03-24 13:47
its fixed in master

**Comment by manast** [comment] 2016-03-24 21:13
fixed in https://github.com/OptimalBits/bull/tree/v1.0.0-rc

**Closed by manast** 2016-03-24 21:13 UTC

**Comment by kylezhang** [comment] 2017-07-19 08:53
https://github.com/NodeRedis/node_redis/issues/1102
