### ISSUE TITLE
Missing process handler for job type __default__

### ISSUE THREAD

**Issue by rj-david** [OptimalBits/bull#1529] opened 2019-10-31 08:03 UTC
## Description
We are getting a 'failed' and 'error' event with the following message: `Missing process handler for job type __default__`

#### (An easy to reproduce test case will dramatically decrease the resolution time.)
We do not know where it is coming among all the jobs running in our system

## Bull version
3.10.0

**Comment by stansv** [comment] 2019-10-31 14:29
Hi! Looks like you use [named processors](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md), i.e. when you define processing callback with name like
```
queue.process('some-name', async (job) => {  })
```
and then add jobs as usual without  setting that `some-name`, so bull uses `__default__` as default:

```
queue.add({ "input": "data" }, ... opts);
```

So either define process callback without setting name (1st arg) or only add jobs to queue to match one of names you use. Finally you can always add named processor for `__default__` as well —
```
queue.process('__default__', async (job) => {  })
```

**Comment by rj-david** [comment] 2019-10-31 15:07
Thanks for this @stansv 

Trying to find if we ever define this un-named job. As of now, cannot find any. Still looking...

**Comment by rj-david** [comment] 2019-11-01 01:43
We cannot find any job with an "un-named" parameters.

But we tried creating a processor for `__default__` but we are still getting the errors

**Comment by gabegorelick** [comment] 2019-11-06 03:26
Related issues:
#1500
#1479
#1377
#1334
#1222

I also see this issue in production from time to time. We also give all jobs names.

**Comment by manast** [comment] 2019-11-06 09:41
The named processors feature has been just a root of confusion, thats why this has been removed from BullMQ (aka bull 4).

**Comment by andrewda** [comment] 2021-04-27 14:07
We're still seeing this on production occasionally, with all our processes named. Have there been any developments here, or has anyone figured out how to circumvent the issue? Does adding a processor for `__default__` really work? It's difficult to test any "solution" when I have no idea how to reproduce the issue.

**Comment by manast** [comment] 2021-04-27 20:29
@andrewburgess not sure why you did thumb me down, but the error you are getting is the reason this feature has been removed from bullmq. You are probably adding a job without specifying a name and you do have workers that do not handle the unnamed job so when that job is fetched by that worker it does not know what to do with it and hence you get the error.

**Comment by gabegorelick** [comment] 2021-04-27 20:37
> You are probably adding a job without specifying a name and you do have workers that do not handle the unnamed job

I can't speak for @andrewburgess, but a lot of people (including myself) have experienced this issue despite the fact that we most definitely do not enqueue any jobs without names. It's some kind of weird race condition in Bull, or something like that.

**Comment by manast** [comment] 2021-04-27 21:14
@gabegorelick provide a proof then :).

**Comment by gabegorelick** [comment] 2021-04-27 21:18
Believe me, if I could provide a reproducible, reliable, minimal test case, I'd already have a fix up.

**Comment by andrewburgess** [comment] 2021-04-27 22:51
In the immortal words of Shaggy, [It Wasn't Me](https://open.spotify.com/track/0OaunKfsxkgBvPv68jBbmm)

**Comment by manast** [comment] 2021-04-28 04:38
@gabegorelick even without a reproducible test case, some more info would help to at least start looking at it. For example, what information can you gather about this particular jobs? could you add extra data to the job data so that it is easier to see a pattern, are this jobs special in any way, why is the name missing if the name property is created in redis at the moment of the job creation?, etc. From my perspective it is impossible to do any debugging since I am unable to reproduce it, and all of the references you posted above are closed issues where the poster discovered they did a mistake. In fact I am inclined to close this issue to avoid speculation and the like until somebody can provide more information.

**Comment by gabegorelick** [comment] 2021-04-30 15:30
@manast I understand. Unfortunately I can't really provide any more information. If I ever figure out the issue, I'll be sure to post an update. Until then, if you prefer to close the issue then I understand.

**Closed** 2021-04-30 16:34 UTC

**Comment by FahmyChaabane** [comment] 2022-02-23 12:21
Hi, I am still getting this error, even tho i don't have any unnamed processor in my app.. Any workaround for this one please?

**Comment by manast** [comment] 2022-02-23 16:47
@FahmyChaabane example code that demonstrates the issue in a new issue, please.

**Comment by FahmyChaabane** [comment] 2022-02-28 21:23
@manast 
My bad! it seems like the issue was cause by me. 

The thing is, i was running a redis instance on a local K8s cluster with 2 replicas. And that caused the issue ( maybe because a worker did notify his working state to redis instance1 and not redis instance2 ? ).. However, having only 1 redis instance works perfectly correct.

here's the example i worked on : https://github.com/FahmyChaabane/Dummy-Nest-BullQueues
