### ISSUE TITLE
SyntaxError: Unexpected token o in JSON at position 0 

### ISSUE THREAD

**Issue by themuflon** [OptimalBits/bull#614] opened 2017-07-11 15:34 UTC
Hi!

I'm getting an error when JSON.parse tries to parse the `job.returnvalue` when processing `job.finished`. Actually, [this](https://github.com/OptimalBits/bull/blob/master/lib/job.js#L330) is where it fails. Typically that would be a JSON string, but rarely, when under heavy load and running on slow/few CPUs (our continuous integration), it's an object (thus the character is "o").

I was wondering if there is anything I'm doing wrong that should be common practice or if it's a bug? I went through the bull codebase but can't figure out what's going wrong.

Also, here's a code snippet of the code that produces the issue.
```
static postJob(queue:Queue.Queue, args:any):Promise<any> {
        var result = queue.add(args).then((_job) => {
            return _job.finished();
        });

        return Promise.resolve(result);
    }
```
The processing side is nothing special either, just some code that eventually calls `done()` with an object.

**Comment by marshall007** [comment] 2017-07-11 15:44
I believe this was fixed in #580, which was released in `v.3.0.0-rc.3`. @themuflon I assume you're still on `v.3.0.0-rc.2`?

**Comment by themuflon** [comment] 2017-07-11 15:47
I'm on `v.3.0.0-rc.4`. Like I said, this shows up only under specific circumstances. 99.99% of the time it works fine.

**Comment by manast** [comment] 2017-07-11 19:08
@themuflon could you by any chance get an error callstack? that would be quite useful to help finding the root cause of this.

**Comment by themuflon** [comment] 2017-07-11 21:36
```SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at /usr/local/src/app/node_modules/bull/lib/job.js:330:24
    at tryCatcher (/usr/local/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/src/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/src/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/src/app/node_modules/bluebird/js/release/async.js:17:14)
From previous event:
    at /usr/local/src/app/node_modules/bull/lib/job.js:326:48
From previous event:
    at Job.finished (/usr/local/src/app/node_modules/bull/lib/job.js:323:36)
    at queue.add.then (/usr/local/src/app/src/jobs/jobs.ts:51:25)
From previous event:
    at Function.postJob (/usr/local/src/app/src/jobs/jobs.ts:49:38)```

All the way down to the code in the original post that adds the job.

**Comment by manast** [comment] 2017-07-11 22:25
ok, so it seems to me that the problem is that in some situation, the returnvalue is stored in the job without having being stringified. I will try to understand how this can possibly can happen in all the code paths that store the returnvalue in the job.

**Comment by nkiraly** [comment] 2017-07-12 16:58
I am seeing this with 3.0.0-rc4.
fromJSON does
`JSON.parse(json.returnvalue)`
but so does Job.prototype.finished promise when job is already completed,
`return  JSON.parse(job.returnvalue); `

it looks like we just need to
`return job.returnvalue;`

please consider  pull request #617

**Comment by manast** [comment] 2017-11-05 21:15
This issue should not happen anymore. Re-open if that is not the case.

**Closed by manast** 2017-11-05 21:15 UTC
