### ISSUE TITLE
example not working: calling close inside process

### ISSUE THREAD

**Issue by mattkrick** [OptimalBits/bull#497] opened 2017-04-18 06:34 UTC
Per the readme, I tried the following:
```
const foo = Queue('foo');
foo.process((job, done) => {
  foo.close();
  done()
});
foo.add(1);
```

The result was an error in the terminal:
`Error processing job: Error: Connection is closed.`

Now, the following _does_ work:

```
const foo = Queue('foo');
foo.process((job) => {
  foo.close();
  return Promise.resolve()
});
foo.add(1);
```

Unless I wrap it in a Promise, then I get the same error:
```
const oneTime = () => {
  return new Promise((resolve) => {
    const temporaryQueue = Queue('foo');
    temporaryQueue.process((job) => {
      temporaryQueue.close()
      resolve(job.data);
      return Promise.resolve();
    });
  });
};
```

Is this working as expected? Any guidance on how to do properly write the 3rd example without leaks?

**Comment by manast** [comment] 2017-04-18 08:17
The problem is that you are closing the queue before it manages to move the job from *active* to *completed* status, since you are closing before calling done(). If you want to be sure the job has been moved before calling close you should listen to the 'completed' events, something like this:

```js
const foo = Queue('foo');
foo.process((job, done) => {
  done()
});
foo.add(1);

foo.once('completed', function(){
  foo.close();
});

```

**Comment by manast** [comment] 2017-04-18 08:53
I have to apologise. Your code should work as well, we even have unit tests for that: https://github.com/OptimalBits/bull/blob/master/test/test_queue.js#L96

**Comment by manast** [comment] 2017-04-18 09:06
This is working on the 3.0.0 branch though, where many simplifications have been made, so it is difficult to backport to 2.x. I recommend you to use the described workaround until 3.0.0 is released. Btw, even if you get an error in the terminal, I think the code worked as it should.

**Comment by mattkrick** [comment] 2017-04-18 14:39
Sounds great, thanks for the fast response!

For the future readers out there that can't upgrade to v3.0, I solved this by putting a listener on `completed`:

```
oneTimeQueue.on('completed', () => {
      setTimeout(() => {
        oneTimeQueue.close();
      }, 100);
    });
```

**Closed** 2017-05-24 12:33 UTC
Labels: bug
