### ISSUE TITLE
Queue prematurely processes delayed jobs

### ISSUE THREAD

**Issue by evanhuang8** [OptimalBits/bull#187] opened 2015-09-25 20:48 UTC
This occurs when a concurrency is set for the process function, say, 5. Say if I schedule 100 delayed jobs that are supposed to be executed 10s later, several jobs will (usually 5-7 for 100 jobs scheduled) be processed immediately, and then processed again later on when they are due.

After some digging, I think the process of adding delayed jobs is flawed:

Currently when a delayed job is added to the queue, it is first added to the `wait` list. When a process handler is added, it goes through the following sequence:

`wait` -> `active` -> `delayed`

However, the process routine, goes like this:

`processStalledJobs` -> `delayIfNeeded`

Here comes the problem, when there are multiple processing routines running (which is the norm in a distributed deployment), there is a chance that `processStalledJobs` will snatch the job before it is moved to the delayed set, since `waiver` -> `active` and `active` -> `delayed` are broken into two steps instead of one single transaction. Therefore, some jobs will be processed prematurely, and again when they are due later on.

One way to solve this is to skip the `active` middle step, but rather make a routine that throws jobs into `delayed` straight from `wait`, that way `processStalledJobs` should not interfere with the delayed jobs.

**Comment by manast** [comment] 2015-09-25 23:24
I think you are right actually. In order to do what you propose, we need that brpoplpush can be called from a LUA script as a blocking call, but I am not sure if that is a good thing since it may create locks on redis that degrade its performance. I will need to investigate more about this. And please keep me posted if you have any ideas :).

**Comment by evanhuang8** [comment] 2015-09-25 23:28
Yeah I tried to create a method that adds the job directly to `delayed`:

```javascript
Job.prototype._addToDelayed = function(delayTimestamp){
  var queue = this.queue;
  var jobId = this.jobId;

  //
  // Bake in the job id first 20 bits into the timestamp
  // to guarantee correct execution order of delayed jobs
  // (up to 1M jobs per given timestamp or 1M jobs apart per timestamp)
  //
  delayTimestamp = delayTimestamp * 0x1000 + (jobId & 0xfff);

  var script = [
    'if redis.call("EXISTS", KEYS[3]) == 1 then',
    ' local score = tonumber(ARGV[1])',
    ' redis.call("ZADD", KEYS[1], score, ARGV[2])',
    ' score = score / 0x1000',
    ' redis.call("PUBLISH", KEYS[1], score)',
    ' return 0',
    'else',
    ' return -1',
    'end'
    ].join('\n');

  var keys = _.map([
    'delayed',
    'jobs',
    jobId], function(name){
      return queue.toKey(name);
    }
  );

  return queue.client.evalAsync(
    script,
    keys.length,
    keys[0],
    keys[1],
    keys[2],
    delayTimestamp,
    jobId).then(function(result){
      if(result === -1){
        throw new Error('Missing Job ' + jobId + ' when trying to add job to delayed');
      }
    });
};
```

And I changed the `Queue.add` method:

```javascript
Queue.prototype.add = function(data, opts){
  var _this = this;
  opts = opts || {};

  //
  // If we fail after incrementing the job id we may end having an unused
  // id, but this should not be so harmful (NOTE: we could create and add the job
  // atomically if we wanted using a proper LUA script)
  //
  return _this.client.incrAsync(this.toKey('id')).then(function(jobId){
    return Job.create(_this, jobId, data, opts);
  }).then(function(job){
    if(job.delay){
      var jobDelayedTimestamp = job.timestamp + job.delay;
      if(jobDelayedTimestamp > Date.now()){
        return job._addToDelayed(jobDelayedTimestamp).then(function(){
          return job;
        });
      }
    }
    return addJob(_this, job.jobId, opts).then(function(){
      _this.emit('waiting', job);
      return job;
    });
  });
};
```

But the delayed tests are stuck, no jobs are getting promoted, probably related to the behavior you said.

**Comment by manast** [comment] 2015-09-25 23:33
yeah, the problem is a bit tricky, specially if we want to solve it without changing to a polling based design...

**Comment by manast** [comment] 2015-09-25 23:44
to minimize the problems we could also check in processStalledJob if the job should be delayed. It will not solve the problem completely since it can happen that it is not delayed when the call to processStalledJob happens but it is still going to be moved to the delayed set on a different process...

**Comment by evanhuang8** [comment] 2015-09-26 16:07
That's still not OK, we need to make sure it's 100% solid since this compromise the integrity of the queue. I will keep thinking of solutions.

**Comment by manast** [comment] 2015-09-26 17:18
I fully agree. The main problem is that moving a job from one queue to another cannot be combined with any other operation in an atomical fashion. Thats the reason we have the need for lockers, because  what happens with delayed jobs (that they can be executed in the process stalled jobs function), can also happen with normal non delayed jobs, if a new process starts when a job is between having being moved to the active queue and starting to be processed. It happens that sometimes the process stalled jobs "steals" a job from the normal process job function, but no harm is done since the worker will not start executing until it has a lock. Therefore we need a similar mechanism here, the process stalled jobs should check if the job should be delayed, if not start it. If the job happens to be on the delay queue and still at the moment process stalled jobs it does not need to be delayed anymore, then it can be executed. The important thing is that when a job is promoted from delay to wait, we need to check if it is already being executed or succeed/failed and in that case just ignore it... I am a bit reluctant about all this because it seems quite complex with many moving parts, which can of course lead to more obscure edge cases and strange bugs...

**Comment by evanhuang8** [comment] 2015-09-27 20:40
Any updates? I am going to look at it more today

**Comment by manast** [comment] 2015-09-27 20:42
I have not thought more about it more than my previous reflexion...

**Comment by evanhuang8** [comment] 2015-09-28 22:04
@manast Please check out the PR. Basically I bypassed the `wait` set but instead I add the job straight into `delayed` at the moment of creation, and everything else works fine.

Also I identify an issue with the queue: technically a worker should only start processing when the queue emits the `ready` event, because the delay timer needs to be updated by listening to the `delayed` channel. If the worker prematurely starts processing while the `eclient` is not yet setup, that the delayed timer can simply go into limbo, since the new timestamp from the `updateDelayedSet` is not received by `eclient`.

I fixed the issue in the tests related to delayed jobs, but I think other tests can benefit from listening to the `ready` event first as well.

**Comment by manast** [comment] 2015-09-29 05:02
@evanhuang8 interesting. Could the solution be so simple?, good job! :)
A few notes, with this new implementation do we still need to check for delayed jobs when getting the jobs? (the infamous delayIfNeededin Queue.prototype.processJobs.
Also, when we are at it, I think we should emit an event 'delayed' for jobs that are delayed, to follow the same pattern as with jobs that are waiting.
Finally, regarding the issue with redis ready. I think that if we need to wait for redis to be ready we should definitely do it inside the queue, the user of the queue should not need to do this manually, but, if there is a risk the delay timer "goes into limbo", this risk will remain even if listening to this event, just a disconnection or some other hazard could lead to this state, for instance pub/sub does not guarantee that the messages are really received by all the clients... so this needs to be addressed in order to make it really bullet proof.

**Comment by evanhuang8** [comment] 2015-09-29 05:09
Yeah it seems that bypassing it should be the way, but do a sanity check if you can. As for `delayIfNeeded`, I am hesitant to take it out - how about retries? Say, if we want to implement a backoff on the retries, having it there might still be necessary.

I agree that we should emit the event as well, should I add to the pull request?

Regarding the timer, how about we do a combo of interval + event? Basically, if we get a null from the `updateDelayTimer`, instead of not doing anything, we set it to check in, say, 5mins, which shouldn't add much burden to the queue but still adds a catch to the uncertainty of pub/sub.

**Comment by manast** [comment] 2015-09-29 05:41
the retries should use the new functionality where they are moved to the delay set directly. If we keep the old, broken, functionality it will not work in some situations.

Regarding adding the polling mechanism, feels like a poor's man solution, but maybe there is nothing better we can do...

**Comment by evanhuang8** [comment] 2015-09-29 06:10
If such is that external information/channel is ultimately unreliable, then the worker itself will have to poll... I think it's OK as long as the polling interval is reasonable. Maybe we should add an option to customize the interval as well?

On a side note, any thoughts on timeline? I am quite eager to start using bull in my projects, but will definitely like to see all the new changes merged in first.

**Comment by manast** [comment] 2015-09-29 16:24
As soon as we are happy with the implementation I can merge and create a new version with it.

**Comment by evanhuang8** [comment] 2015-09-29 16:29
Cool. I can add all the stuff today, so the list is:

* Add a polling mechanism in addition to the current setup
* Emit `delayed` event for delayed jobs
* Implement automatic retries and backoffs

Let me know if anything is missing

**Comment by manast** [comment] 2015-09-29 16:46
also remove the delayIfNeeded and the need for waiting to redis 'ready' event :)

**Comment by evanhuang8** [comment] 2015-09-29 16:46
Will do

**Comment by evanhuang8** [comment] 2015-09-29 21:56
@manast Alright all changes pushed to the PR, the cluster test somehow fails on the CI but it runs fine every time I run it on my local computer, so not sure what's going on here - maybe it's just a IPC delay issue? But yeah please check out the PR, thanks!

**Closed** 2015-09-30 21:51 UTC
