### ISSUE TITLE
Recommended way of cleaning up finished jobs?

### ISSUE THREAD

**Issue by framerate** [OptimalBits/bull#73] opened 2015-01-10 02:39 UTC
I noticed that my redis instance gets larger and larger with completed jobs.

What's the recommended way to cull these and keep it neat and tidy?

**Comment by manast** [comment] 2015-01-10 08:59
Hello, this is a duplicate of this https://github.com/OptimalBits/bull/issues/24

**Closed by manast** 2015-01-10 08:59 UTC

**Comment by framerate** [comment] 2015-01-10 17:21
Awesome thanks!



—
-jhttp://framerate.io
